package/gdal: fix license hash
license hash is wrong since the addition of the package in commit
3191c12f6cc4c12b66df7cba369fd9fdf4672110:

ERROR: LICENSE.TXT has wrong sha256 hash:
ERROR: expected: b82e6cca0b13f5db2f22ab667f22254fb1f4b135ea73d5bd6238ef89aff31f6c
ERROR: got     : fac0116e799ca4de79b076ee04863b5e2b69541ea3664b9bb108c81a5355f16a
ERROR: Incomplete download, or man-in-the-middle (MITM) attack

Fixes:
 - http://autobuild.buildroot.org/results/e443db6d7ff3ae867035d169853b880b5e13d181

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>