package/pkg-cargo.mk: fix debug build
There is no --debug mode for cargo resulting in the following build
failure in ripgrep since its conversion to cargo infrastructure in
commit 3bd0de30008b38af9c389695af6002ecb81f97e1:

error: Found argument '--debug' which wasn't expected, or isn't valid in this context

Fixes:
 - http://autobuild.buildroot.org/results/772ebdd6a39950457a59419bdc1376cb0e0a3611

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>