package/python3-cffi: bump version to 1.14.6
- the last version bump of package/python-cffi (4a9345e) ignored
  the comment 'Please keep in sync with package/python3-cffi/python3-cffi.mk',
  so catch up now

Fixes:

  ERROR: No hash found for cffi-1.14.2.tar.gz

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>