package/zeek: disable with libressl
Disable building with libressl to avoid the following build failure
raised since the addition of the package in commit
94e6c3b1ddfcbe4dedd2b92bc0fce08ed39614de:

In file included from /home/thomas/autobuild/instance-2/output-1/build/zeek-4.1.1/src/analyzer/protocol/mime/MIME.cc:7:
/home/thomas/autobuild/instance-2/output-1/build/zeek-4.1.1/src/zeek/digest.h: In function 'void* EVP_MD_CTX_md_data(const EVP_MD_CTX*)':
/home/thomas/autobuild/instance-2/output-1/build/zeek-4.1.1/src/zeek/digest.h:22:12: error: invalid use of incomplete type 'const EVP_MD_CTX' {aka 'const struct env_md_ctx_st'}
   22 |  return ctx->md_data;
      |            ^~

Fixes:
 - http://autobuild.buildroot.org/results/2db2988d495f9d06d058fb532a2dcfa9ef6e207c

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 30f7c1b1970a4a8a5d8bb968082a9c58a1c85ef5)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>