package/uhd: fix build of examples
Fix the following build failure raised since the addition of the package
in commit 38916b88505e7ccb1fb4e91295ceba62b61a8ed6:

../lib/libuhd.so.3.15.0: undefined reference to `int boost::math::sign<double>(double const&)'

Fixes:
 - http://autobuild.buildroot.org/results/a38856930b20a0d6fda28fe52f8a4c90c9df4e3a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>