package/janet: fix static build
Fix the following static build failure raised since commit
b1f42a97059a4d26ff4f2100addd245ba264f2aa:

/home/giuliobenetti/autobuild/run/instance-0/output-1/host/bin/xtensa-buildroot-linux-uclibc-gcc  -o janet janet.p/meson-generated_.._janet.c.o janet.p/src_mainclient_shell.c.o -Wl,--as-needed -Wl,--allow-shlib-undefined -Wl,-O1 -Wl,--start-group -latomic -lm -ldl -Wl,--end-group -pthread
/home/giuliobenetti/autobuild/run/instance-0/output-1/host/lib/gcc/xtensa-buildroot-linux-uclibc/10.3.0/../../../../xtensa-buildroot-linux-uclibc/bin/ld: /home/giuliobenetti/autobuild/run/instance-0/output-1/host/lib/gcc/xtensa-buildroot-linux-uclibc/10.3.0/libgcc.a(unwind-dw2-fde-dip.o): in function `_Unwind_Find_registered_FDE':
/home/giuliobenetti/autobuild/run/instance-0/output-1/build/host-gcc-final-10.3.0/build/xtensa-buildroot-linux-uclibc/libgcc/../../../libgcc/unwind-dw2-fde.c:1043: undefined reference to `dl_iterate_phdr'

Fixes:
 - http://autobuild.buildroot.org/results/d6cd842bd156abe3d77b72a7a108a5233fa19e20

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>