package/luasyslog: bump to version 2.2.1
This bump contains a single commit which fixes the following build
failure with Lua 5.4 raised since commit
b46981ee1cdea36ba8ac805dfe42f166b81e9013:

In file included from lsyslog.c:11:
compat-5.3.h:402:4: error: #error "unsupported Lua version (i.e. not Lua 5.1, 5.2, or 5.3)"
  402 | #  error "unsupported Lua version (i.e. not Lua 5.1, 5.2, or 5.3)"
      |    ^~~~~

Also update indentation in hash file (two spaces)

Fixes:
 - http://autobuild.buildroot.org/results/df2aabcf2ae07cad66b869ec4ac76702d2c32dc5

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Romain Naour <romain.naour@gmail.com>
Tested-by: Romain Naour <romain.naour@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>