package/softhsm2: requires DES support in openssl
Fix the following build failure raised since the addition of the package
in commit 8925928454a9f5bc3a28d42ae52f11d86e7fb8a4:

OSSLDES.cpp: In member function 'virtual const EVP_CIPHER* OSSLDES::getCipher() const':
OSSLDES.cpp:81:12: error: 'EVP_des_cbc' was not declared in this scope; did you mean 'EVP_sm4_cbc'?
   81 |     return EVP_des_cbc();
      |            ^~~~~~~~~~~
      |            EVP_sm4_cbc

Fixes:
 - http://autobuild.buildroot.org/results/27d471c4ad1cdd5f2332b949f71cba86723d349f

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>