package/tesseract-ocr: override neon check
Override neon check to avoid the following build failure with uclibc-ng
raised since bump to version 5.0.1 in commit
be0567e4c032422b8c02893d45a85c7e70916a99:

src/arch/simddetect.cpp:61:14: fatal error: sys/auxv.h: No such file or directory
   61 | #    include <sys/auxv.h>
      |              ^~~~~~~~~~~~

It should be noted that a patch to properly fix this build failure was
rejected by upstream as "ARM support without NEON would result in a very
slow Tesseract": https://github.com/tesseract-ocr/tesseract/pull/3717

So, a follow-up patch adding a dependency on !BR2_TOOLCHAIN_USES_UCLIBC
for all CPU architectures or only for ARM without NEON could be
approriate.

Fixes:
 - http://autobuild.buildroot.org/results/0bac6491188b6681df2ca13eb230706e83cbb130

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>