package/libcurl: fix build without sched_yield
Fix the following build failure without sched_yield raised since bump to
version 7.84.0 in commit 48542704fd3561fe6359c7bc730f7791452da527:

In file included from easy.c:89:
easy_lock.h: In function 'curl_simple_lock_lock':
easy_lock.h:56:7: error: implicit declaration of function 'sched_yield' [-Werror=implicit-function-declaration]
   56 |       sched_yield();
      |       ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/fbc80a0002d640210c81a4c518856c02669059b7

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Baruch Siach <baruch@tkos.co.il>
Tested-by: Giulio Benetti <giulio.benetti@benettiengineering.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>