package/network-manager: needs gcc >= 4.9
network-manager needs gcc >= 4.9 since bump to version 1.32.2 in commit
7621e8b9f8dfa0c63fe40e04def6651e073d208e to avoid the following build
failure:

src/libnm-core-impl/nm-setting-bond.c: At top level:
src/libnm-core-impl/nm-setting-bond.c:149:5: error: array initialized from non-constant array expression
     NM_MAKE_STRV("stable", "bandwidth", "count");
     ^

Fixes:
 - http://autobuild.buildroot.org/results/dc270ead82707f89d47616a0c18629715c6ea1a5

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>