package/janet: fix build without threads
Fix the following build failure without threads raised since bump to
version 1.26.0 in commit 438bb066b7ba079a5b3880052db097cc4a95786a:

ffi.c:(.text+0x9d8): undefined reference to `janet_abstract_threaded'

Fixes:
 - http://autobuild.buildroot.org/results/20108e76990d8af7f47d474eadbbea8562ef6728

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>