package/libglvnd: needs dynamic library
libglvnd needs dynamic library since the addition of the package in
commit 69725563e969774c4861060bda7725b70dda85f6:

/libglvnd_pthread.a.p/glvnd_pthread.c.o -c ../src/util/glvnd_pthread.c
../src/util/glvnd_pthread.c:33:10: fatal error: dlfcn.h: No such file or directory
   33 | #include <dlfcn.h>
      |          ^~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/c5e92f0b355c91cdcebe0070499889473996f337

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>