package/python-pymupdf: add missing host swig dependency
It appears that python-pymupdf needs swig when building since mupdf
was bumped to 1.18.0 in commit
1a7b9da3fb6aa38aabc8381936cd87ec751ee1b3. This was not noticed before
because when building on a machine where swig is already available
outside buildroot, it is used and the build succeeds.

This fixes the following build failure:

swigging fitz/fitz.i to fitz/fitz_wrap.c
swig -python -w509 -o fitz/fitz_wrap.c fitz/fitz.i
error: command 'swig' failed: No such file or directory
make: *** [package/pkg-generic.mk:293:
/home/buildroot/autobuild/instance-2/output-1/build/python-pymupdf-1.21.1/.stamp_built]
Error 1

Fixes:
- http://autobuild.buildroot.net/results/c689a385d984b87b63f3f2ff30338049774b1bf2
- http://autobuild.buildroot.net/results/cf268d3631330a8288fb8ad2af009abb7f1ca6b0

Signed-off-by: Raphaël Mélotte <raphael.melotte@mind.be>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit 0b20ba1cbc562a988b606ca46a7e68d400e9aabb)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>