package/osm2pgsql: needs gcc >= 4.9
osm2pgsql needs C++14 since bump to version 1.5.1 in commit
7b6e3d3967c358952ee28dc753af7825dcc8c262 and
https://github.com/openstreetmap/osm2pgsql/commit/d35dd358d6e4a88a792be60c85bf55d2360c1a71
to avoid the following build failure:

/home/buildroot/autobuild/instance-1/output-1/build/osm2pgsql-1.5.1/src/db-copy.cpp: In member function 'void db_copy_thread_t::sync_and_wait()':
/home/buildroot/autobuild/instance-1/output-1/build/osm2pgsql-1.5.1/src/db-copy.cpp:108:16: error: 'make_unique' is not a member of 'std'
     add_buffer(std::make_unique<db_cmd_sync_t>(std::move(barrier)));
                ^

Fixes:
 - http://autobuild.buildroot.org/results/30ae4b9405454919437098d29abbd743638c9423

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Maxim Kochetkov <fido_max@inbox.ru>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>