package/kbd: needs gcc 4.9
kbd uses _Generic since version 2.2.90 and
https://github.com/legionus/kbd/commit/da5feb8fd90c3a0df9d505d4604c629d051d3d7d

However, _Generic is not available until gcc 4.9:
https://gcc.gnu.org/wiki/C11Status

As a result, build with gcc 4.8 fails on:

setleds.c:352:3: warning: implicit declaration of function '_Generic' [-Wimplicit-function-declaration]
   ndefflags = BITMASK_SET(BITMASK_UNSET(odefflags, ndef), nval);
   ^
setleds.c:22:2: error: expected expression before 'unsigned'
  unsigned char: (unsigned char)(~(x)) \
  ^

Fixes:
 - http://autobuild.buildroot.org/results/b74ecdda44543da1d47fa2c027fb046a3ca1e2d1

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
[yann.morin.1998@free.fr: propagate the MMU dependency to the comment]
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>