package/network-manager: needs headers >= 4.6
network-manager uncondtionally uses ETHTOOL_GLINKSETTINGS since version
1.31.3 and
https://github.com/NetworkManager/NetworkManager/commit/4a81fe13ae18cb6d157d7cb3eec300f3061263fe
which is only available since kernel 4.6 and
https://github.com/torvalds/linux/commit/3f1ac7a700d039c61d8d8b99f28d605d489a60cf
resulting in the following build failure since commit
7621e8b9f8dfa0c63fe40e04def6651e073d208e:

In file included from ./src/libnm-glib-aux/nm-default-glib.h:69:0,
                 from ./src/libnm-glib-aux/nm-default-glib-i18n-lib.h:13,
                 from src/libnm-platform/nm-platform-utils.c:6:
src/libnm-platform/nm-platform-utils.c: In function '_ethtool_cmd_to_string':
src/libnm-platform/nm-platform-utils.c:280:51: error: 'ETHTOOL_GLINKSETTINGS' undeclared (first use in this function)
                                 NM_UTILS_ENUM2STR(ETHTOOL_GLINKSETTINGS, "ETHTOOL_GLINKSETTINGS"),
                                                   ^

Fixes:
 - http://autobuild.buildroot.org/results/10b9b68ab6987b99b3e8dfb2d651808008ad0bb7

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>