package/poco: requires DES support in openssl
Fix the following build failure raised since commit
9a2800a14115a604ce8c1d00b842eca0f551995c:

src/EVPPKey.cpp:161:52: error: 'EVP_des_ede3_cbc' was not declared in this scope; did you mean 'SN_des_ede3_cbc'?
  161 |      rc = PEM_write_bio_PrivateKey(bio, _pEVPPKey, EVP_des_ede3_cbc(),
      |                                                    ^~~~~~~~~~~~~~~~
      |                                                    SN_des_ede3_cbc

Fixes:
 - http://autobuild.buildroot.org/results/eddcba8e74c23ea041f2d95de57196107f5af8a3

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>