package/quazip: doesn't build with zlib-ng
quazip doesn't build with zlib-ng since bump to version 1.9.9-b1 in
commit 6fb35153976d995c599ee785252441d802cd1968 and the removal of
z_crc_t and FAR:
https://github.com/zlib-ng/zlib-ng/commit/4db4cfdb5badc8860f7410732b12c45216d709b3
https://github.com/zlib-ng/zlib-ng/commit/0db1040667b13c0f9405af810f669857a487b08e:

/nvmedata/autobuild/instance-16/output-1/build/quazip-1.2/quazip/unzip.c:196:11: error: unknown type name 'z_crc_t'
  196 |     const z_crc_t FAR * pcrc_32_tab;
      |           ^~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/02272c154ce58bacf0518dab5fc1ef0084121e1a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>