package/aircrack-ng: fix sqlite3 build
Fix the following build failure raised since bump to version 1.2 in
commit aaae403b830d58e6c9a1d0d06e14502d39debae8:

powerpc-buildroot-linux-gnu-gcc: WARNING: unsafe header/library path used in cross-compilation: '-I/usr/include'
In file included from src/aircrack-ng/aircrack-ng.c:54:
/usr/include/math.h:476:21: error: '_Float128' is not supported on this target
  476 | # define _Mdouble_  _Float128
      |                     ^~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/83a114ce197fb6af53a26ed68184cf3bbb30c8a7

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>