package/ruby: needs gcc and host gcc >= 4.9
ruby needs gcc and host gcc >= 4.9 since commit
adcaec2e7aacbff50a72b5716209718ac92c90bf and the addition of AC_PROG_CC:

In file included from vm_core.h:85:0,
                 from iseq.h:14,
                 from mini_builtin.c:3,
                 from miniinit.c:51:
thread_pthread.h:108:43: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'struct'
     RUBY_EXTERN RB_THREAD_LOCAL_SPECIFIER struct rb_execution_context_struct *ruby_current_ec;
                                           ^

Fixes:
 - http://autobuild.buildroot.org/results/f196f8bc68d1b4c20bddced89478598a3fcd3dea
 - http://autobuild.buildroot.org/results/81bdac585600877d3fa8d9478b7f160dbd1537a9

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>