package/re2: fix build with gcc <= 5
Fix the following build failure with gcc <= 5 raised since bump to
version 2022-02-01 in commit a5c0ff31478fa9a1b260f92d7c2e8db36c39f486
and
https://github.com/google/re2/commit/a022cc0c55b0519629d64d775e7a5195af34a477

./re2/sparse_array.h:266:37: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
 SparseArray<Value>::SparseArray() = default;
                                     ^
./re2/sparse_array.h: In copy constructor 're2::SparseArray<Value>::SparseArray(const re2::SparseArray<Value>&)':
./re2/sparse_array.h:273:3: error: 'copy_n' is not a member of 'std'
   std::copy_n(src.sparse_.data(), src.max_size(), sparse_.data());
   ^

Fixes:
 - http://autobuild.buildroot.org/results/8ebbac67f32fe24416a1f72aad0afd42b567b403

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>