package/speechd: fix NLS build
Fix the following NLS build failure raised since the addition of the
package in commit 2a20b00c16c9776c0cbdb826a27d002373786cc5:

/home/buildroot/autobuild/run/instance-2/output-1/host/lib/gcc/arm-buildroot-linux-musleabihf/12.3.0/../../../../arm-buildroot-linux-musleabihf/bin/ld: ../../src/common/.libs/libcommon.a(libcommon_la-i18n.o): undefined reference to symbol 'libintl_bindtextdomain'

Fixes:
 - http://autobuild.buildroot.org/results/8ab13cf474d732c95a1da65592d950b24b3d474b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 350de8827d66f9ea074f81e681cf0ec685fa56db)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>