package/qemu: disable vhost-user with uclibc-ng
Disable vhost-user on uclibc-ng as it raises build failures since bump
to version 6.0.0 in commit 4362083ad25d77e860d21e1823facfeebdc1a596 and
https://github.com/qemu/qemu/commit/810033be083040591fee2fc09f2f294670ed1930

The issue is that F_ADD_SEALS and F_SEAL_xxx variables are not defined on
uclibc-ng (even if MFD_ALLOW_SEALING is defined) resulting in the
following build failure:

../subprojects/libvhost-user/libvhost-user.c:1637:22: error: 'F_ADD_SEALS' undeclared (first use in this function)
 1637 |     ret = fcntl(*fd, F_ADD_SEALS, flags);
      |                      ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/9f393539931b51191cf7128e5c618c2398fc86c1

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
[yann.morin.1998@free.fr: use conditional block like for all other OPTS]
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>