package/mariadb: security bump to version 10.11.6
This bump will fix the following build failure raised since bump of fmt
to version 10.1.0 in commit 7bac1f52945843d556ffa662cfce94ad6595ec69
thanks to
https://github.com/MariaDB/server/commit/f4cec369a392c8a6056207012992ad4a5639965a:

-- Performing Test HAVE_SYSTEM_LIBFMT
-- Performing Test HAVE_SYSTEM_LIBFMT - Failed

[...]

-- Downloading...
   dst='/home/buildroot/autobuild/instance-3/output-1/build/mariadb-10.11.4/extra/libfmt/src/8.0.1.zip'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/fmtlib/fmt/archive/refs/tags/8.0.1.zip'
CMake Error at libfmt-stamp/download-libfmt.cmake:170 (message):
  Each download failed!

    error: downloading 'https://github.com/fmtlib/fmt/archive/refs/tags/8.0.1.zip' failed
          status_code: 1
          status_string: "Unsupported protocol"
          log:
          --- LOG BEGIN ---
          Protocol "https" not supported or disabled in libcurl

This bump will also fix CVE-2023-22084

https://mariadb.com/kb/en/mariadb-10-11-5-release-notes/
https://mariadb.com/kb/en/mariadb-10-11-6-release-notes/

Fixes:
 - http://autobuild.buildroot.org/results/9cb577195aa939289102116df5a2eac03f0d5017

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 1ae38d5771970ccd49aae7091f0691af44de7095)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>