package/memcached: bump to version 1.6.16
This bump will fix the following build failure with gcc 12 thanks to
https://github.com/memcached/memcached/commit/4df826aafdd6abf0fc483d52774047c3533206dc:

In function 'complete_incr_bin',
    inlined from 'dispatch_bin_command' at proto_bin.c:1010:17,
    inlined from 'try_read_command_binary' at proto_bin.c:119:9:
proto_bin.c:272:31: error: array subscript 'protocol_binary_request_incr[0]' is partly outside array bounds of 'char[45]' [-Werror=array-bounds]
  272 |     req->message.body.delta = ntohll(req->message.body.delta);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

https://github.com/memcached/memcached/wiki/ReleaseNotes1616
https://github.com/memcached/memcached/wiki/ReleaseNotes1615
https://github.com/memcached/memcached/wiki/ReleaseNotes1614
https://github.com/memcached/memcached/wiki/ReleaseNotes1613

Fixes:
 - http://autobuild.buildroot.org/results/27ae4bc1ce0d37dee09613b1145023f0d96d8c55

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>