package/gnupg2: fix build without ldap
Buildroot commit 76b777b5f5255f867ea69eff57b78b7366b0e692 bumped the
version of gnupg2 on the next branch causing a build error:

server.c:(.text+0xbf8): undefined reference to `ks_ldap_help_variables'

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 28d7e21e32491a4afad639c742068e847fbc7e45)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>