package/gesftpserver: fix build with gcc 4.8
Fix the following build failure with gcc 4.8 raised since bump to
version 2 in commit 25021b397b6c0daf38e2bc73c6f1ea98ec6d634c and
https://github.com/ewxrjk/sftpserver/commit/dbbf0d45425a72a790d25b889ca2cfa909aaaadf:

In file included from alloc.c:25:0:
utils.h:204:48: error: expected ';', ',' or ')' before 'dest'
 static inline void *sftp_memcpy(void *restrict dest, const void *restrict src,
                                                ^

Fixes:
 - http://autobuild.buildroot.org/results/2795213c07c4a961cee0ae7a4e7cccb8bcd6f68e

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>