package/opensc: requires DES in openssl
Enable DES in openssl to avoid the following build failure raised since
the addition of the package in commit
5228edac25136887c8cd0e04cfe631f115832968:

In file included from sm-common.c:51:
sm-common.h:33:1: error: unknown type name 'DES_LONG'
   33 | DES_LONG DES_cbc_cksum_3des(const unsigned char *in, DES_cblock *output, long length,
      | ^~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/25d0933406dea28201dadc90abd32072afab720b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>