package/erofs-utils: bump to version 1.5
- Drop patches (already in version)
- liberofs is now released under GPL-2.0+ OR Apache-2.0 license:
  https://git.kernel.org/pub/scm/linux/kernel/git/xiang/erofs-utils.git/commit/?id=49b344c5531a7819f282b0b1b6eb01682c0e41ae
- This bump will fix the following build failure on or1k thanks to
  https://git.kernel.org/pub/scm/linux/kernel/git/xiang/erofs-utils.git/commit/?id=100cae2b98a70ac69ae7a09ed94f86ddf8c89fe2

  In file included from ../include/erofs/cache.h:11,
                   from cache.c:9:
  ../include/erofs/internal.h:34:2: error: #error incompatible PAGE_SIZE is already defined
     34 | #error incompatible PAGE_SIZE is already defined
        |  ^~~~~

https://lists.ozlabs.org/pipermail/linux-erofs/2022-June/006462.html

Fixes:
 - http://autobuild.buildroot.org/results/755f8d736b8ad96b213bb3975b26f1143e60e5b5

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Gao Xiang <hsiangkao@aol.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>