package/gr-osmosdr: bump to version 0.2.4
This bump will fix the following build failure raised since bump of
gnuradio to version 3.10.4.0 in commit
205bdb9df9a7ec6dc22aa992552e7bbac29fae71 thanks to
https://github.com/osmocom/gr-osmosdr/commit/159885f9e67101834c100ceb7affc122e3f98bac:

/home/autobuild/autobuild/instance-20/output-1/build/gr-osmosdr-0.2.3/lib/source_impl.cc: In static member function 'static osmosdr::source::sptr osmosdr::source::make(const string&)':
/home/autobuild/autobuild/instance-20/output-1/build/gr-osmosdr-0.2.3/lib/source_impl.cc:105:36: error: could not convert 'gnuradio::get_initial_sptr(T*) [with T = source_impl]()' from 'std::shared_ptr<source_impl>' to 'osmosdr::source::sptr' {aka 'boost::shared_ptr<osmosdr::source>'}
  105 |   return gnuradio::get_initial_sptr( new source_impl(args) );
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                    |
      |                                    std::shared_ptr<source_impl>

https://github.com/osmocom/gr-osmosdr/releases/tag/v0.2.4

Fixes:
 - http://autobuild.buildroot.org/results/5af61d6fb8f8c5d5f91c74a6ef66800236d7bf12

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>