package/python-pycli: drop package
Even with the two upstream patches added in commit
dca556d3344f8a7e2db41b31904bbc05fa4e3204, python-pycli still raises the
following build failure since bump of python3 to version 3.10.1 in
commit fce4948c43ab0e8e83b461fed903b03988172cd2 due to the new "Multiple
Exception types without parentheses" exception
(https://docs.python.org/3/whatsnew/3.10.html):

error:   File "/usr/lib/python3.10/site-packages/cli/test.py", line 142
    except raises, e:
           ^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

So drop the package as the last release was made 10 years ago.

Fixes:
 - http://autobuild.buildroot.org/results/6112e1830ce608abcea4a26b659c10e5ff09a66a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>