package/argp-standalone: fix NLS build
Fix the following build failure raised since bump to version 1.4.1 in
commit c30fd6e9ae46a856b99625c061e5fb2e65f997d4 and
https://github.com/ericonr/argp-standalone/commit/e5fe9ad9e83e6765cf8fa787f903d4c6792338b5:

/home/buildroot/autobuild/instance-2/output-1/host/opt/ext-toolchain/bin/../lib/gcc/mipsel-buildroot-linux-uclibc/10.3.0/../../../../mipsel-buildroot-linux-uclibc/bin/ld: libargp.a(argp-parse.o): in function `argp_version_parser':
/home/buildroot/autobuild/instance-2/output-1/build/argp-standalone-1.4.1/argp-parse.c:181: undefined reference to `libintl_dgettext'

Fixes:
 - http://autobuild.buildroot.org/results/adb9c4b747352497adbc9df866709b17fe0f9755

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>