package/rtorrent: disable execinfo
Disable execinfo to avoid the following build failure raised since the
addition of libexecinfo package in commit
d92bb62c11a0632a4a6a658b762fb1819fd62570:

/home/giuliobenetti/autobuild/run/instance-0/output-1/host/lib/gcc/arc-buildroot-linux-uclibc/10.2.0/../../../../arc-buildroot-linux-uclibc/bin/ld: main.o: in function `do_panic(int)':
/home/giuliobenetti/autobuild/run/instance-0/output-1/build/rtorrent-0.9.8/src/main.cc:606: undefined reference to `backtrace'

Fixes:
 - http://autobuild.buildroot.org/results/10fc9016013931c58238240216c5950b23b56b30

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>