package/boinc: fix build with libexecinfo
Fix the following build failure raised on uclibc and musl since the
addition of libexecinfo package in commit
d92bb62c11a0632a4a6a658b762fb1819fd62570:

/home/buildroot/autobuild/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/arc-buildroot-linux-uclibc/10.2.0/../../../../arc-buildroot-linux-uclibc/bin/ld: ../lib/.libs/libboinc.a(libboinc_la-diagnostics.o): in function `boinc_catch_signal':
diagnostics.cpp:(.text+0x8a): undefined reference to `backtrace'

Fixes:
 - http://autobuild.buildroot.org/results/4504379b464eb144a4c257001eb4d316bb1f5e44

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>