python-setuptools: bump to 40.0.0
With the introduction of Python 3.7.0, setuptools also needs to be updated.
Without the update, several packages will fail to build or install with a
ValueError: bad marshal data (unknown type code).

Updating setuptools to 40.0.0 version fixes this issue.

Even though 40.1.0 is out, updating to 40.0.0 is recommended as it seems like
40.1.0 breaks version detection on some python packages such as
python-cryptography which will error out with a complaint that setuptools is too
old, even though it's at 40.1.0. Using 40.0.0 fixes the issue.

Fixes:
http://autobuild.buildroot.net/results/636/636da0febe02f991095965d52cc4a8b2da644777/
http://autobuild.buildroot.net/results/5f6/5f659130a6a32a4c43d6ed2c3b559df77ae18249/
Signed-off-by: Adam Duskett <aduskett@greenlots.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>