package/libgpgme: fix build without threads
Fix the following build failure without threads raised since bump to
version 1.17.1 in commit a1a117edb323f7548c4e728a8de3fc5bf165511c and
https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=commit;h=f3177d3ee0a1d30e15f33ff226b5e4c96b7610db:

run-wkdlookup.cpp: In function 'int main(int, char**)':
run-wkdlookup.cpp:130:18: error: 'std::this_thread' has not been declared
  130 |             std::this_thread::sleep_for(std::chrono::milliseconds{250 * cnt});
      |                  ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/2915f6105bae595274fabaa12de7cc53926d22d0

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>