package/wayland: fix build with gcc 4.8
Fix the following build failure with gcc 4.8 raised since bump to
version 1.20.0 in commit a9a4f20d18c266274791b4ed967db3ea71462881 and
https://gitlab.freedesktop.org/wayland/wayland/-/commit/80164ef3005e8bb5f785082b97a75cab15444f82:

../src/wayland-util.c: In function 'for_each_helper':
../src/wayland-util.c:373:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (size_t idx = 0; idx < count; idx++) {
  ^
../src/wayland-util.c:373:2: note: use option -std=c99 or -std=gnu99 to compile your code

Fixes:
 - http://autobuild.buildroot.org/results/3040c9a8cf08415a7f4338185f6dc7245c68c64c

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>