package/s390-tools: needs OpenSSL-enabled libcurl
Fix the following build failure raised bump to version 2.17.0 in commit
d97bd687068514590ddd01a8cb435d3c9f1fb136 and
https://github.com/ibm-s390-linux/s390-tools/commit/56fecf1832c3ebc4626ddf5c598762833c362d5e:

Error: libcurl is not built with the OpenSSL backend

Fixes:
 - http://autobuild.buildroot.org/results/32aa8f0bece5da2a16d761f175d46c7d3e0a8965
 - http://autobuild.buildroot.org/results/535253f483c927da456c0be292df6a58c1f39737

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit aa2e1b02dcf27f14ea506138521270cb63c99124)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>