package/lighttpd: add xxhash mandatory dependency
Add xxhash mandatory dependency to avoid the following build failure
with the embedded xxhash (in version 0.8.1) and uclibc raised since
bump to version 1.4.63 in commit
02a26fb09c020a979f0e3fa9de67a137502c7b21 and
https://github.com/lighttpd/lighttpd1.4/commit/23b07fa3efde70b76afa5380b1602d0515aedd46:

/home/buildroot/autobuild/instance-0/output-1/host/lib/gcc/arm-buildroot-linux-uclibcgnueabi/10.3.0/../../../../arm-buildroot-linux-uclibcgnueabi/bin/ld: src/lighttpd.p/algo_xxhash.c.o: in function `XXH32_canonicalFromHash':
/home/buildroot/autobuild/instance-0/output-1/build/lighttpd-1.4.63/build/../src/algo_xxhash.h:2282: undefined reference to `static_assert'

Fixes:
 - http://autobuild.buildroot.org/results/7b644dce244a1aa4a193a3196059a56b2c4c7591

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>