configs/sipeed_*_sdcard: Add dependency on host-openssl
Gitlab CI reported build failures for the sipeed RISC-V nommu boards
with the u-boot/sdcard enabled default configuration. The compilation
errors are related to the openssl/evp.h header file missing, e.g.:

In file included from tools/imagetool.h:24,
                 from tools/fit_common.c:20:
include/image.h:1166:12: fatal error: openssl/evp.h: No such file or
directory
 1166 | #  include <openssl/evp.h>
      |            ^~~~~~~~~~~~~~~

Fix this issue by adding BR2_TARGET_UBOOT_NEEDS_OPENSSL=y to the config
files so that host-openssl gets built as a dependency of U-Boot.

Fixes:
https://gitlab.com/buildroot.org/buildroot/-/jobs/3134229992
https://gitlab.com/buildroot.org/buildroot/-/jobs/3134229994
https://gitlab.com/buildroot.org/buildroot/-/jobs/3134229996
https://gitlab.com/buildroot.org/buildroot/-/jobs/3134229998

Suggested-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
Signed-off-by: Damien Le Moal <damien.lemoal@opensource.wdc.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>