package/grpc: fix build with libexecinfo
Fix the following build failure raised on uclibc and musl since the
reintroduction of the package in commit
1f74ddf62a1c98b65b2a4daa52a7c97c90579fae:

/home/buildroot/autobuild/instance-1/output-1/host/opt/ext-toolchain/bin/../lib/gcc/arm-buildroot-linux-uclibcgnueabi/10.3.0/../../../../arm-buildroot-linux-uclibcgnueabi/bin/ld: /home/buildroot/autobuild/instance-1/output-1/host/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/lib/libabsl_stacktrace.so.2111.0.0: undefined reference to `backtrace'

Fixes:
 - http://autobuild.buildroot.org/results/63ab2bc86cad03d5258492b17d1707078761d9b3

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>