package/btrfs-progs: fix build with kernel < 5.11
Fix the following build failure with kernel < 5.11 raised since commit
3f1c35dde214b2f8721517ee55aee5f4e8d7f17c:

/tmp/instance-1/output-1/host/opt/ext-toolchain/bin/../lib/gcc/powerpc64-buildroot-linux-gnu/9.3.0/../../../../powerpc64-buildroot-linux-gnu/bin/ld: kernel-shared/volumes.o: in function `create_chunk':
volumes.c:(.text+0x17f8): undefined reference to `__ALIGN_KERNEL'

Fixes:
 - http://autobuild.buildroot.org/results/b630dbd078656a974c6ac9645b2e87279ef2adc0

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>