package/pangomm: bump to version 2.48.2
Switch to meson-package as configure is not shipped anymore

This bump will fix the following build failure raised since bump of
pango to version 1.50.3 in commit
51ba75af37fb721dba238e7ab726cc46062a0702:

attrlist.cc: In constructor 'Pango::AttrList::AttrList(const Glib::ustring&, gunichar)':
attrlist.cc:38:20: error: 'pango_parse_markup' was not declared in this scope
   38 |   gboolean bTest = pango_parse_markup(markup_text.c_str(), -1 /* means null-terminated */, accel_marker,
      |                    ^~~~~~~~~~~~~~~~~~

https://gitlab.gnome.org/GNOME/pangomm/-/blob/2.48.2/NEWS

Fixes:
 - http://autobuild.buildroot.org/results/efe5015ddb4bede6669ad5b1e4f027a2e076d16b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>