package/cryptopp: disable altivec if needed
Fix the following build failure raised since commit
9ed85997ff1fdaad6e0d8d1a336960d643234b20:

blake2s_simd.cpp:715:8: error: 'uint32x4_p' does not name a type; did you mean 'uint32_t'?
  715 | inline uint32x4_p VecLoad32(const T* p)
      |        ^~~~~~~~~~
      |        uint32_t

Fixes:
 - http://autobuild.buildroot.org/results/9e9f8559b12b8e2cf99cfab435fa7dd5796bbcd5

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>