package/util-linux: fix libuuid build
Fix the following build failure raised since bump to version 2.37.2 in
commit 97e6ea26aaf57f6a89d0987ba1e79e8266b7c6ea and
https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git/commit/?id=33b09aebf505acfbbb2137319093fbb9ed7eea7d

libuuid/src/unparse.c:42:73: error: expected ';', ',' or ')' before 'fmt'
 static void uuid_fmt(const uuid_t uuid, char *buf, char const *restrict fmt)
                                                                         ^

Fixes:
 - http://autobuild.buildroot.org/results/b931a34a47e5faf8ae48fce079747dea0db2563a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
[yann.morin.1998@free.fr: use symlink for util-linux-libs patch]
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>