package/diffutils: fix build on arceb
Fix the following build failure raised since bump to version 3.8 in
commit 3ec719078daff331cc57d8573decc40089f1233e:

sigsegv.c: In function 'sigsegv_handler':
sigsegv.c:979:28: error: 'struct vma_struct' has no member named 'is_near_this'
  979 |                       : vma.is_near_this (addr, &vma))
      |                            ^

Fixes:
 - http://autobuild.buildroot.org/results/8c5b8b37eb3c2667c75666079b056df7e0023e05

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>