package/pipewire: fix build on powerpc
Fix the following build failure raised since bump to version 0.3.39 in
commit 679c60871e882ab1bc93247e0b2eeadd2d81386e:

In file included from /home/giuliobenetti/autobuild/run/instance-1/output-1/host/powerpc-buildroot-linux-uclibc/sysroot/usr/include/signal.h:318,
                 from ../spa/include/spa/utils/defs.h:34,
                 from ../spa/include/spa/utils/type.h:32,
                 from ../spa/include/spa/support/log.h:34,
                 from ../spa/plugins/support/cpu.c:37:
../spa/plugins/support/cpu.c: In function 'impl_init':
../spa/plugins/support/cpu.c:88:33: error: called object is not a function or function pointer
   88 | #define impl_cpu_zero_denormals NULL
      |                                 ^~~~

Fixes:
 - http://autobuild.buildroot.org/results/eaf255c46b10cbb6b8a629bc15acf7772d5e274b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>