package/kompexsqlite: security bump to version 1.12.15
- Update site to get latest version
- Switch to generic-package and drop patches as upstream doesn't provide
  autotools support
- License is MIT since version 1.12.15
- This bump will fix the following build failure with BR2_OPTIMIZE_FAST:

src/sqlite3.c: In function 'sqlite3IsNaN':
src/sqlite3.c:21797:3: error: #error SQLite will not work correctly with the -ffast-math option of GCC.
21797 | # error SQLite will not work correctly with the -ffast-math option of GCC.
      |   ^~~~~

- This bump will also fix security issues by bumping sqlite to 3.36.0
- Update indentation in hash file (two spaces)

http://sqlitewrapper.kompex-online.com/index.php?content=changelog

Fixes:
 - http://autobuild.buildroot.org/results/63e07345b97faa6d6239933f1790c6f2e02da77f

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>