package/lxc: fix build with sys/pidfd.h
Fix the following build failure with sys/pidfd.h raised since bump to
version 5.0.1 in commit cab84524e1b8276f90f0b7d38b073f361331ce84:

In file included from ../src/lxc/utils.h:23,
                 from ../src/lxc/cgroups/cgfsng.c:51:
../src/lxc/process_utils.h:140:17: error: expected identifier before numeric constant
  140 | #define P_PIDFD 3
      |                 ^

Fixes:
 - http://autobuild.buildroot.org/results/c9ff42a921ca47f634f908bab80c80164c227a02

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>