package/tinifier: fix license hash
license hash is wrong since the addition of the package in commit
df3815e0e31a892752b8649b3be9b31e3838993c:

>>> tinifier 3.4.0 Collecting legal info
ERROR: LICENSE has wrong sha256 hash:
ERROR: expected: 791d8fd993ace44d4d83e2f4820a64d5ad3e37412f029afad46d17a9259de2b6
ERROR: got     : 18f524914c0df04e21289c3d9ca3e27c10abe5869cc4e4d4790a1b2c56df282c

Fixes:
 - http://autobuild.buildroot.org/results/5fce7f16daca17216d786391ea0fffff856c5404

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>