package/crun: needs gcc >= 4.9
crun unconditionally uses atomic_bool when libgcrypt is found since
version 1.7.1 and
https://github.com/containers/crun/commit/40f66c0a74b8d918ecc7ae9228dca32a4fd71084
resulting in the following build failure with gcc 4.8 since commit
e59e53529d3b70de6bafa46c581544947dfbf70d:

src/libcrun/seccomp.c: In function 'calculate_seccomp_checksum':
src/libcrun/seccomp.c:374:3: error: unknown type name 'atomic_bool'
   static atomic_bool initialized = false;
   ^

Fixes:
 - http://autobuild.buildroot.org/results/924806ffd6d83cd6d8226577c3877b0b8ca2722d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Christian Stewart <christian@paral.in>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>