package/python-aiohttp-sse: bump to version 2.1.0
License hash change due to full text removal:
https://github.com/aio-libs/aiohttp-sse/commit/307fd35a84a66b7fb5adfd70cd5b7d709fa8508c

Fixes(python 3.10 compatibility):
  File "/usr/lib/python3.10/site-packages/aiohttp_sse/__init__.py", line 107, in wait
  File "/usr/lib/python3.10/site-packages/aiohttp_sse/__init__.py", line 144, in _ping
TypeError: sleep() got an unexpected keyword argument 'loop'

Signed-off-by: James Hilliard <james.hilliard1@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>