package/python-pycli: fix build with python >= 3.10
Fix the following build failure raised since bump of python3 to version
3.10.1 in commit fce4948c43ab0e8e83b461fed903b03988172cd2 due to the new
"Multiple Exception types without parentheses" exception
(https://docs.python.org/3/whatsnew/3.10.html)

error:   File "/usr/lib/python3.10/site-packages/cli/app.py", line 242
    except Exception, e:
           ^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

Fixes:
 - http://autobuild.buildroot.org/results/8d7b0c23472abffc9447e4a6de273bdd04486d39

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>