package/gobject-introspection: needs host gcc >= 7
Commit 89d9d12cc02065854e0dce27d6bf05fe3d8b8458 forgot to propagate
host gcc >= 7 dependency to reverse dependencies of host-qemu resulting
in the following build failure:

ERROR: You need at least GCC v7.5 or Clang v6.0 (or XCode Clang v10.0)

Fixes:
 - http://autobuild.buildroot.org/results/14cd0250d55c5ca5dc1d297aee1b927fda889531

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>