package/pure-ftpd: doesn't build with libressl
pure-ftpd doesn't build with libressl 3.4.3 which doesn't include
https://github.com/libressl-portable/openbsd/commit/f5674b4e2330b382bacefd3393affc8eb2ee2ba8
resulting in the following build failure:

tls.c: In function 'tls_init_options':
tls.c:329:5: warning: implicit declaration of function 'SSL_CTX_set_num_tickets'; did you mean 'SSL_CTX_set_options'? [-Wimplicit-function-declaration]
     SSL_CTX_set_num_tickets(tls_ctx, 0);
     ^~~~~~~~~~~~~~~~~~~~~~~
     SSL_CTX_set_options

Fixes:
 - http://autobuild.buildroot.org/results/f5d36180949278510199aa499e253780558c6ffe

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>