package/putty: disable gssapi
PUTTY_GSSAPI is enabled by default resulting in the following build
failure since bump to version 0.78 in commit
fcd0a5f4ef6b86ed71b44c978e1bfb30b8d0414b:

 /home/fabrice/buildroot/output/build/putty-0.79/unix/gss.c:133:10: fatal error: gssapi/gssapi.h: No such file or directory
  133 | #include <gssapi/gssapi.h>
      |          ^~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/d6d06b5aa0df070c3880399e044fb3cd3a830aec

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit d43d5e07fc7b855221dd8d91ab6a53ed3d81971b)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>