package/mc: fix build with gcc 4.8
Fix the following build failure with gcc 4.8 raised since bump to
version 4.8.26 in commit e5a6d4b4a6f725d505ef44c2163579c873d2037b and
https://github.com/MidnightCommander/mc/commit/8b4386df83ab5a525f0568113fe1e53d362f433e:

tty-ncurses.c: In function 'tty_colorize_area':
tty-ncurses.c:575:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (int row = 0; row < rows; row++)
     ^

Fixes:
 - http://autobuild.buildroot.org/results/d9f0a11bde42fe6ae2e9449d3365609d59a6545d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>