package/libsoup: fix build with gcc 4.8
Fix build failure with gcc 4.8 which is raised since bump to version
2.72.0 in commit d1776119bf0e6c17e177145cf17dc9bfe46b41f4:

In file included from /tmp/instance-0/output-1/host/arm-buildroot-linux-gnueabi/sysroot/usr/include/resolv.h:65:0,
                 from /tmp/instance-0/output-1/host/arm-buildroot-linux-gnueabi/sysroot/usr/include/glib-2.0/gio/gnetworking.h:40,
                 from ../libsoup/soup-address.c:14:
/tmp/instance-0/output-1/host/arm-buildroot-linux-gnueabi/sysroot/usr/include/arpa/nameser.h:115:2: error: unknown type name 'u_char'
  const u_char *_msg, *_eom;
  ^

Fixes:
 - http://autobuild.buildroot.org/results/56b9cb987e25b99d6fed16c537552f47c3376f21

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Adrian Perez de Castro <aperez@igalia.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>