package/libblockdev: needs locale
locale_t is unconditionally used since version 1.5 and
https://github.com/storaged-project/libblockdev/commit/4ed6f0b3a46fc77554dab661c22150829aa75966
resulting in the following build failure since the addition of the
package in commit 1e930f76c4420f75f81f4ff91883219597fac037:

module.c:33:37: error: unknown type name 'locale_t'
   33 | static char *strerror_l(int errnum, locale_t locale UNUSED)
      |                                     ^~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/ede9eb1f13d56c77005cc448416fb2efa9d16ff0

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>