package/linux-tools: perf needs dynamic library
traceevent needs dynamic library since its addition in kernel 3.14 and
https://github.com/torvalds/linux/commit/c877bbd8eceb14c5eac6779cc804fa8b34044736:

event-plugin.c:10:10: fatal error: dlfcn.h: No such file or directory
   10 | #include <dlfcn.h>
      |          ^~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/24206071721479a6ba4d0267e7e20ef9498e1e05

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>