package/libuhttpd: depends on gcc >= 4.9
Add a dependency on gcc >= 4.9 to avoid the following build failure
with gcc 4.8.3 raised since bump to version 3.14.1 in commit
9ecb862ac4d4b0fd6417d5dc4ef5d2adba9aa800 and
https://github.com/zhaojh329/libuhttpd/commit/ffdf7de3a4a1f5a62aa3814ac96e889958a30840:

/home/peko/autobuild/instance-1/output-1/build/libuhttpd-3.14.1/src/cgi.c:41:5: error: initializer element is not a constant expression [-Werror]
     {"accept", strlen("accept"), "HTTP_ACCEPT"},
     ^

It should be noted that upstream rejected a patch to remove -Werror:
https://github.com/zhaojh329/libuhttpd/pull/12

Fixes:
 - http://autobuild.buildroot.org/results/a3a970a6398dcb0e4e03f4277f1a50c6b5eff7bd

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>