package/mtd: update lib{mtd,ubi}.h path
Update lib{mtd,ubi}.h path to fix the following build failure raised
since bump of swupdate to version 2021.04 in commit
a632fa9ec0e684354a6447676b354b9056e3bd9d:

In file included from corelib/mtd-interface.c:21:
include/flash.h:13:10: fatal error: libmtd.h: No such file or directory
   13 | #include <libmtd.h>
      |          ^~~~~~~~~~

This build failure is raised because of
https://github.com/sbabic/swupdate/commit/0c672866d4a9fe8f0808b5d8a0afb95c13c4c138

Fixes:
 - http://autobuild.buildroot.org/results/d475bdb341d2afecf12e404dfa093e58221b9882

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>