package/poco: needs C++17
poco needs C++17 and gcc >=8 since bump to version 1.13.2 in commit
2bb10eaf716ff49ffcb165f29f223f5dfef13bd8 and
https://github.com/pocoproject/poco/commit/78234857bf416b718455496800d1b7be3a0d0a53
https://github.com/pocoproject/poco/commit/10f41c06d9416a6ae0884c4827ea2a91bf5d2cf8
resulting in the following build failure with gcc 7:

In file included from src/Thread.cpp:28:0:
src/Thread_POSIX.cpp: In member function 'void Poco::ThreadImpl::setNameImpl(const string&)':
src/Thread_POSIX.cpp:162:56: error: no matching function for call to 'std::__cxx11::basic_string<char>::append(const string&, std::__cxx11::basic_string<char>::size_type)'
   truncName.append(threadName, threadName.size() - half);
                                                        ^

Fixes: 2bb10eaf716ff49ffcb165f29f223f5dfef13bd8
 - http://autobuild.buildroot.org/results/7b1c144f39a8be4ce8f964aa13a52d0bf62dd0aa

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>
(cherry picked from commit 8e12f153331124cec9b792f4913e1dcb1ab5467d)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>