package/pipewire: compress-offload needs kernel >= 5.7
SND_AUDIOCODEC_A{LAC,PE} are only available since kernel 5.7 and
https://github.com/torvalds/linux/commit/0f546d6f0292fb624b4cf0cc70096ddb9ea070e6
resulting in the following build failure since bump to version 0.3.65
in commit c02ebaa0a80ae1193ffed34b80f515db03dc87f8 and
https://git.buildroot.net/buildroot/commit/?id=c02ebaa0a80ae1193ffed34b80f515db03dc87f8:

../spa/plugins/alsa/alsa-compress-offload-sink.c:183:11: error: 'SND_AUDIOCODEC_ALAC' undeclared here (not in a function); did you mean 'SND_AUDIOCODEC_AAC'?
  183 |         { SND_AUDIOCODEC_ALAC, },
      |           ^~~~~~~~~~~~~~~~~~~
      |           SND_AUDIOCODEC_AAC

Moreover, flac_d is also only available since kernel 5.5 and
https://github.com/torvalds/linux/commit/d2522335c92c090bf58531a2b696d7fe80ab2a7a

Take this opportunity to make compress offload an explicit option rather
than automatic based on the availability of tinycompress. The
relationship between them is not obvious.

Fixes:
 - http://autobuild.buildroot.org/results/9ecd9aca5edc3756154da59573157954f06e6537

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>