package/python-cryptography: add missing openssl build dependency
Commit
61db1e3a9e962ffacd770b9b2499502b83d8bfae ("package/python-cryptography:
bump version to 36.0.1") incorrectly removed the build dependency on
openssl. This causes the following build failure:

build/temp.linux-x86_64-3.10/_openssl.c:575:10: fatal error: openssl/opensslv.h: No such file or directory
  575 | #include <openssl/opensslv.h>
      |          ^~~~~~~~~~~~~~~~~~~~

as OpenSSL is no longer guaranteed to be built before
python-cryptography (the Config.in file still had a "select
BR2_PACKAGE_OPENSSL" guaranteeing that OpenSSL would be built, but not
necessarily before).

Signed-off-by: James Hilliard <james.hilliard1@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>