package/qemu: qemu systems emulation needs fdt when building for all targets
defconfig fragment to reproduce the issue:
BR2_PACKAGE_QEMU_ARCH_SUPPORTS_TARGET=y
BR2_PACKAGE_QEMU=y
BR2_PACKAGE_QEMU_SYSTEM=y

ERROR: Problem encountered: fdt not available but required by targets
       aarch64-softmmu, arm-softmmu, i386-softmmu, loongarch64-softmmu,
       microblaze-softmmu, microblazeel-softmmu, mips64el-softmmu,
       nios2-softmmu, or1k-softmmu, ppc-softmmu, ppc64-softmmu,
       riscv32-softmmu, riscv64-softmmu, rx-softmmu, x86_64-softmmu

Commit [1] select BR2_PACKAGE_QEMU_FDT for each individual emulator targets
but forgot to select is when BR2_PACKAGE_QEMU_CHOOSE_TARGETS is not set
(building for all targets).

Fixes:
http://autobuild.buildroot.org/results/e44/e444a02b899d325a9d99daed96b8cb96108383e7

[1] 44bdc2ce2b94147119ca14818a30518274635d10

Signed-off-by: Romain Naour <romain.naour@smile.fr>
Cc: Carlos Santos <unixmania@gmail.com>
Cc: Yann E. MORIN <yann.morin.1998@free.fr>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 4c44f7f1e80b4b3fd56f148201a7b96bc5a012bc)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>