package/openfpgaloader: bump to current master
- argp is no more used;
- UDEV dependency is now optional

Fix:
- http://autobuild.buildroot.org/results/f3f3cc216ae42bb8a8925b0df7c1a3cc79b027d7

/home/buildroot/autobuild/instance-1/output-1/build/openfpgaloader-849e5751e06d4d00f323205d5f02ee01f9f59a61/src/spiFlash.cpp:
In member function 'void SPIFlash::jtag_write_read(uint8_t, uint8_t*, uint8_t*, uint16_t)':
/home/buildroot/autobuild/instance-1/output-1/build/openfpgaloader-849e5751e06d4d00f323205d5f02ee01f9f59a61/src/spiFlash.cpp:92:43:
error: variable-sized object 'jtx' may not be initialized
  uint8_t jtx[xfer_len] = {reverseByte(cmd)};
                           ^
and

src/gowin.cpp:73:11: error: 'runtime_error' is not a member of 'std'
 throw std::runtime_error("both write-flash and write-sram can't be set");
       ^
src/gowin.cpp:81:10: error: 'runtime_error' is not a member of 'std'
  throw std::runtime_error("incompatible file format");

Signed-off-by: Gwenhael Goavec-Merou <gwenhael.goavec-merou@trabucayre.com>
[yann.morin.1998@free.fr:
  - don't add a sub-option for udev; directly rely on udev being avail
  - fix conflict after 19beedc1283a
]
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>