package/python-numpy: needs C++
C++ is mandatory since at least version 1.23.0 and
https://github.com/numpy/numpy/commit/c91a7d0c5691c9d78bd75284777fda73f225155d
resulting in the following build failure since bump to version 1.23.4 in
commit 868a9417f535430e84bf5bbb45d05a8d933fce8f:

RuntimeError: Broken toolchain: cannot link a simple C++ program. note: A compiler with support for C++11 language features is required.

Fixes:
 - http://autobuild.buildroot.org/results/2d048d9b669ad60f37eeb2162b0a4f9fb425be1e

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>