package/lightning: needs threads
threads are mandatory since bump to version 2.2.0 in commit
cbec343b4e19afc1b97578ecc4a9153204466624 and
https://git.savannah.gnu.org/cgit/lightning.git/commit/?id=d5a7c8e4ad719e84dbb4904c532f906a1ef5a77b:

In file included from incr.c:2:
../include/lightning.h:27:10: fatal error: pthread.h: No such file or directory
   27 | #include <pthread.h>
      |          ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/62205869159d4a73c59a9795140fa77e9c3310ae

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>