package/poco: bump version to 1.12.2
poco 1.12.0 updated its pcre depencency to pcre2, see:
https://github.com/pocoproject/poco/blob/poco-1.12.2-release/CHANGELOG#L37
The Kconfig selection and dependencies are updated accordingly. This
commit also reorder those Kconfig options alphabetically.

This commit adds an upstream patch to fix compilation failure with
oracle-mysql. See:
https://github.com/pocoproject/poco/commit/3884c734c261231c34f59e56cde7ae02945b4dae

This commit also adds "-latomic" to ldflags at configuration time, if
the toolchain has it. This is required for some architecture: without
this, compilation with bootlin-riscv64-glibc toolchain (for example)
fails at link time with undefined reference to '__atomic_exchange_1'.
The --ldflags option was introduced in 1.12.0 (Thanks Fabrice). See:
https://github.com/pocoproject/poco/pull/3545

For the full Poco change log since 1.11.12, see:
https://github.com/pocoproject/poco/blob/poco-1.12.2-release/CHANGELOG

Signed-off-by: Julien Olivain <ju.o@free.fr>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>