package/ipcalc: fix static build
Fix the following static build failure raised since commit
29652f2baf3b69ca9cd445dd3f3abcee50e9af09:

../ipcalc-maxmind.c:41:11: fatal error: dlfcn.h: No such file or directory
   41 | # include <dlfcn.h>
      |           ^~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/5f867aeab9c61538e34b14023d0ba327698d3c04

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>