package/opensc: fix libressl build
Fix the following build failure with libressl >= 3.8 raised since bump
of libressl to version 3.8.2 in commit
595388c0e922450efeee0948777b0c2e34e46291:

In file included from card-westcos.c:37:
/home/autobuild/autobuild/instance-11/output-1/host/arm-buildroot-linux-gnueabi/sysroot/usr/include/openssl/evp.h:627:32: error: macro "EVP_sha3_224" passed 1 arguments, but takes just 0
  627 | const EVP_MD *EVP_sha3_224(void);
      |                                ^

Fixes:
 - http://autobuild.buildroot.org/results/cecee659371f370bf4bd2b27a4752bf20ceff326

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit 6b21088a96de3bf3ded33d54a1175abd362ed121)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>