package/php-apcu: needs threads
php-apcu needs threads since its addition in commit
096ce54158d61a425f7e2d492abed1494a86c9dc:

In file included from /home/buildroot/autobuild/instance-3/output-1/build/php-apcu-5.1.20/apc_lock.c:20:
/home/buildroot/autobuild/instance-3/output-1/build/php-apcu-5.1.20/apc_lock.h:41:11: fatal error: pthread.h: No such file or directory
   41 | # include "pthread.h"
      |           ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/314405423aeece5ee55d76ec5c4fa1919e7ee853

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Acked-by: Herve Codina <herve.codina@bootlin.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>