package/liburing: needs MMU
liburing needs MMU since its addition in commit
7ac9f78d5966d1d8998516065977eec0be98fe29:

setup.c: In function 'io_uring_ring_dontfork':
setup.c:119:8: warning: implicit declaration of function 'madvise'; did you mean 'raise'? [-Wimplicit-function-declaration]
  119 |  ret = madvise(ring->sq.sqes, len, MADV_DONTFORK);
      |        ^~~~~~~
      |        raise

Fixes:
 - http://autobuild.buildroot.org/results/33f3c58e98daab07139b4f400b85f87c0e314240

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>