package/python-docker: needs python-packaging after bump to 6.0.1
Commit f9d2522cf7dd31 (package/python-docker: bump to version 6.0.1) forgot
to add the new dependency on python-packaging, leading to runtime errors:

  import docker
    File "/usr/lib/python3.11/site-packages/docker/__init__.py", line 2, in <module>
    File "/usr/lib/python3.11/site-packages/docker/api/__init__.py", line 2, in <module>
    File "/usr/lib/python3.11/site-packages/docker/api/client.py", line 10, in <module>
    File "/usr/lib/python3.11/site-packages/docker/auth.py", line 7, in <module>
    File "/usr/lib/python3.11/site-packages/docker/utils/__init__.py", line 3, in <module>
    File "/usr/lib/python3.11/site-packages/docker/utils/decorators.py", line 4, in <module>
    File "/usr/lib/python3.11/site-packages/docker/utils/utils.py", line 9, in <module>
  ModuleNotFoundError: No module named 'packaging'

Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 2fd17c192d9b7e4c4c0949fea76b1ef6f5b90baa)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>