package/bluez-alsa: needs alsa-lib mixer
aplay needs alsa-lib mixer since bump to version 4.0.0 in commit
7f012664690dbad0f1f8f34f20768870740dfa9b and
https://github.com/Arkq/bluez-alsa/commit/7050c9a81895500fe2d59ec6e4859633d4353e36:

In file included from alsa-mixer.c:11:
alsa-mixer.h:16:21: error: unknown type name 'snd_mixer_t'; did you mean
'snd_timer_t'?
   16 | int alsa_mixer_open(snd_mixer_t **mixer, snd_mixer_elem_t
      **elem,
      |                     ^~~~~~~~~~~
      |                     snd_timer_t

So select BR2_PACKAGE_ALSA_LIB_MIXER instead of building aplay
conditionally to keep backward compatibility

Fixes:
 - http://autobuild.buildroot.org/results/d3faac6e49fe9cc21091a5dfa44780b8c63189be

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>