package/rust-bin: fix armv7-unknown-linux-gnueabi
Commit ac8576315dc6c2f8720e83cae59325b8b6f08487 forgot to add hash for
armv7-unknown-linux-gnueabi resulting in the following build failure:

ERROR: No hash found for rust-std-1.54.0-armv7-unknown-linux-gnueabi.tar.xz

Fixes:
 - http://autobuild.buildroot.org/results/443f94bb9ae0addb5130f96fb363ec9651e8af3d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>