package/mdio-tools: needs fork
Fix the following build failure raised since the addition of the package
in commit f33f42775200f3f200246d9c3462c81d478e0ae1:

mdio.c: In function 'mdio_modprobe':
mdio.c:738:15: error: implicit declaration of function 'fork' [-Werror=implicit-function-declaration]
  738 |         pid = fork();
      |               ^~~~

Fixes:
 - http://autobuild.buildroot.org/results/c53aaeaa34dd4d6d9a57da196687beecaeed9fe2

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Joachim Wiberg <troglobit@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>