package/zbar: fix python build
Fix the following build failure with python raised since its activation
by commit 9db5d3fe1e85967c5f41dbccedbadfc08a47d401:

In file included from /home/giuliobenetti/autobuild/run/instance-2/output-1/host/include/python3.9/Python.h:63,
                 from python/zbarmodule.h:24,
                 from python/zbarmodule.c:24:
/home/giuliobenetti/autobuild/run/instance-2/output-1/host/include/python3.9/pyport.h:741:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  741 | #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
      |  ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/43a8c8d5403c329f2d754ed09807a53772174397

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>