package/connman: fix build with libexecinfo
Fix the following build failure raised on uclibc and musl since the
addition of libexecinfo package in commit
d92bb62c11a0632a4a6a658b762fb1819fd62570:

/home/peko/autobuild/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/x86_64-buildroot-linux-uclibc/10.3.0/../../../../x86_64-buildroot-linux-uclibc/bin/ld: src/backtrace.o: in function `print_backtrace':
backtrace.c:(.text+0x37): undefined reference to `backtrace'

Fixes:
 - http://autobuild.buildroot.org/results/74da4f4deab5f0ae9405d063ad52a5d4904a964d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>