package/mpv: needs gcc >= 4.9
Fixes:
http://autobuild.buildroot.net/results/e41/e41f0a779d46565d448a1d20cf5e17060d9a70b8/

Quoted from build/config.log
err: ../test.c:1:23: fatal error: stdatomic.h: No such file or directory

This header was added with gcc-4.9:
https://gcc.gnu.org/gcc-4.9/changes.html
"ISO C11 atomics (the _Atomic type specifier and qualifier and the
 <stdatomic.h> header) are now supported."

According to
https://github.com/mpv-player/mpv/commit/06718da79c79a98d5524f42d034b0d406b14e04c
"In theory, a user can still use --disable-stdatomic to enable the
 emulation code, but that's sort of hidden. Actual support will be
 removed after the next release or so."

Although adding --disable-stdatomic could fix the current issue we
require gcc >= 4.9 now to follow the recommendation from upstream.

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>