package/olsr: backport upstream patch to fix compat with gpsd 3.21
Since the update of gpsd to 3.21, olsr was failing to build with:

src/gpsdclient.c: In function 'nmeaInfoFromGpsd':
src/gpsdclient.c:373:14: error: 'struct gps_data_t' has no member named 'status'
  373 |   if (gpsdata->status == STATUS_NO_FIX) {
      |              ^~

This is due to an API change in gpsd. This commit fixes that by
backporting an upstream commit from olsr.

Fixes:

  http://autobuild.buildroot.net/results/d8c5564b24ff5b646cdd786d07b3a45ce5fa01ea/

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>