package/rpi-rgb-led-matrix: fix build with gcc 4.8
Fix the following build failure with gcc 4.8 raised since the addition
of the package in commit 8e12f8672ded0e67f204a6e65e7ad21b098ec5d3:

In file included from framebuffer.cc:20:0:
framebuffer-internal.h:83:10: error: 'constexpr' does not name a type
   static constexpr int kBitPlanes = 11;
          ^
framebuffer-internal.h:83:10: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11

Fixes:
 - http://autobuild.buildroot.org/results/c035da0d183f21343f19f7dee982e8e73ee781e4

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>