package/bcusdk: fix build with argp-standalone and NLS
Fix the following build failure with argp-standalone and NLS raised
since commit 93feff506dad5d9f0e81e94ab5cf7784c68b01d5:

configure:16428: /home/buildroot/autobuild/instance-3/output-1/host/bin/sh4-linux-gcc -o conftest -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os -g0  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  conftest.c -largp   >&5
/home/buildroot/autobuild/instance-3/output-1/host/opt/ext-toolchain/bin/../lib/gcc/sh4-buildroot-linux-uclibc/10.3.0/../../../../sh4-buildroot-linux-uclibc/bin/ld: /home/buildroot/autobuild/instance-3/output-1/host/sh4-buildroot-linux-uclibc/sysroot/usr/lib/libargp.a(argp-parse.o): in function `argp_version_parser':
/home/buildroot/autobuild/instance-3/output-1/build/argp-standalone-1.4.1/argp-parse.c:190: undefined reference to `libintl_dgettext'

[...]

checking for library containing argp_parse... no
configure: error: argp_parse not found

Fixes:
 - http://autobuild.buildroot.org/results/9277a064b61f24ad35334b318fe4d899a4c39aa1

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>