package/optee-client: fix build without plugins
Fix the following build failure raised since bump to version 3.17.0 in
commit 8909743c3e7ab60afb91b4b2cd53b80e9fd4f9b0 and
https://github.com/OP-TEE/optee_client/commit/876b1ae719e12890ddd96e85cd4e9862dab46448:

/home/giuliobenetti/autobuild/run/instance-2/output-1/build/optee-client-3.17.0/tee-supplicant/src/tee_supplicant.c:104:22: error: 'TEE_PLUGIN_LOAD_PATH' undeclared here (not in a function); did you mean 'TEEC_LOAD_PATH'?
  104 |  .plugin_load_path = TEE_PLUGIN_LOAD_PATH,
      |                      ^~~~~~~~~~~~~~~~~~~~
      |                      TEEC_LOAD_PATH

Fixes:
 - http://autobuild.buildroot.org/results/384e0ca894dbc0ec72cea76141de890f1ce484db

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>