package/libdbi: needs dynamic library
libdbi needs dynamic library to avoid the following build failure raised
since the addition of the package in commit
a907851d208a28613cfd4c679a2c5a649beb90ef:

dbi_main.c:84:2: error: #error no dynamic loading support
   84 | #error no dynamic loading support
      |  ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/9cd56a625cbd52b0c070e2d462e02f5161d9631d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>