package/firmware-utils: needs dynamic library
As usual with cmake packages, static builds are not supported and result
in the following build failure:

/home/buildroot/autobuild/instance-1/output-1/host/opt/ext-toolchain/bin/../lib/gcc/powerpc-buildroot-linux-uclibc/9.3.0/../../../../powerpc-buildroot-linux-uclibc/bin/ld: /home/buildroot/autobuild/instance-1/output-1/host/powerpc-buildroot-linux-uclibc/sysroot/usr/lib/libcrypto.a(c_zlib.o): in function `zlib_stateful_expand_block':
c_zlib.c:(.text+0x54): undefined reference to `inflate'

Instead of patching CMakeLists.txt to add a call to pkg-config, add a
dependency on dynamic library

Fixes:
 - http://autobuild.buildroot.org/results/16a89075e6a809a551e7155a64a4e6b6701428e1

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>