package/rtl8812au-aircrack-ng: bump to version 37e27f9165300c89607144b646545fac576ec510
Fix the following build failure with kernel >= 5.17 thanks to
https://github.com/aircrack-ng/rtl8812au/commit/7e61ad89ccae51a80706f765e1d5f2e82a1662c7:

/home/autobuild/autobuild/instance-14/output-1/build/rtl8812au-aircrack-ng-3a6402e9e79802891f1531b435be54f4d8b71f0b/./os_dep/osdep_service.c: In function ‘thread_exit’:
/home/autobuild/autobuild/instance-14/output-1/build/rtl8812au-aircrack-ng-3a6402e9e79802891f1531b435be54f4d8b71f0b/./os_dep/osdep_service.c:1295:2: error: implicit declaration of function ‘complete_and_exit’ [-Werror=implicit-function-declaration]
 1295 |  complete_and_exit(comp, 0);
      |  ^~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/1fff5023b5b79a7d81fd4cba6dea8dcb3f428340

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>