package/libpsl: fix build with libiconv
Fix the following build failure raised since the addition of the package
in commit 34a9f748c7328ab5995d2ca21d46b0bc161795b4:

/home/autobuild/autobuild/instance-9/output-1/host/lib/gcc/sparc-buildroot-linux-uclibc/10.3.0/../../../../sparc-buildroot-linux-uclibc/bin/ld: src/libpsl.so.5.3.2.p/psl.c.o: in function `psl_str_to_utf8lower':
psl.c:(.text+0x1584): undefined reference to `libiconv_open'

Fixes:
 - http://autobuild.buildroot.org/results/8f012331acd3edb96a69d374436884679add8860

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>