package/firmware-utils: requires DES support in openssl
Fix the following build failure raised since the addition of the package
in commit 4128d787d16d0c1c96ef0ef7e8020e24701961b2:

/home/giuliobenetti/autobuild/run/instance-0/output-1/build/firmware-utils-86739f2b3ae9502368b89ef37fa6f31c42aad6f4/src/mkhilinkfw.c:54:8: error: unknown type name 'DES_key_schedule'
   54 | static DES_key_schedule schedule;
      |        ^~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/0563b24ccb7dd242998e1b59b217405c6340e276

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>