package/gqrx: bump to version 2.15.9
This bump will fix the following build failure raised since bump pf
gnuradio to version 3.10.4.0 in commit
205bdb9df9a7ec6dc22aa992552e7bbac29fae71:

In file included from /home/buildroot/autobuild/instance-2/output-1/build/gqrx-2.14.4/src/applications/gqrx/receiver.cpp:32:
/home/buildroot/autobuild/instance-2/output-1/build/gqrx-2.14.4/src/applications/gqrx/receiver.h:34:10: fatal error: gnuradio/blocks/wavfile_sink.h: No such file or directory
   34 | #include <gnuradio/blocks/wavfile_sink.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

https://github.com/gqrx-sdr/gqrx/blob/v2.15.9/resources/news.txt

Fixes:
 - http://autobuild.buildroot.org/results/42b5ab2e555063273ea55fd1c09a9be6d8b620e2

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>