package/postgresql: select mandatory libopenssl features
Select mandatory libopenssl features (which are selectable since
commit 9a2800a14115a604ce8c1d00b842eca0f551995c):

- BR2_PACKAGE_LIBOPENSSL_ENABLE_BLOWFISH
- BR2_PACKAGE_LIBOPENSSL_ENABLE_CAST
- BR2_PACKAGE_LIBOPENSSL_ENABLE_DES

Fixes:

  - http://autobuild.buildroot.net/results/7fdcaa337a7369673ac4580ff7a2bbccc895dca2

  openssl.c:449:35: warning: implicit declaration of function 'EVP_bf_ecb'; did you mean 'EVP_sm4_ecb'? [-Wimplicit-function-declaration]
    449 |  if (!EVP_EncryptInit_ex(evp_ctx, EVP_bf_ecb(), NULL, NULL, NULL))
        |                                   ^~~~~~~~~~
        |                                   EVP_sm4_ecb
  openssl.c:449:35: warning: passing argument 2 of 'EVP_EncryptInit_ex' makes pointer from integer without a cast [-Wint-conversion]
    449 |  if (!EVP_EncryptInit_ex(evp_ctx, EVP_bf_ecb(), NULL, NULL, NULL))
        |                                   ^~~~~~~~~~~~
        |                                   |
        |                                   int
  In file included from openssl.c:34:
  .../host/arm-buildroot-linux-uclibcgnueabihf/sysroot/usr/include/openssl/evp.h:583:53: note: expected 'const EVP_CIPHER *' {aka 'const struct evp_cipher_st *'} but argument is of type 'int'
    583 |                                   const EVP_CIPHER *cipher, ENGINE *impl,
        |                                   ~~~~~~~~~~~~~~~~~~^~~~~~

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>