package/cryptopp: needs wchar
Fix the following build failure raised since commit
9ed85997ff1fdaad6e0d8d1a336960d643234b20:

In file included from seckey.h:11,
                 from 3way.h:10,
                 from 3way.cpp:5:
misc.h:1528:6: error: 'wstring' in namespace 'std' does not name a type
 1528 | std::wstring StringWiden(const char *str, bool throwOnError = true);
      |      ^~~~~~~
In file included from seckey.h:11,
                 from 3way.h:10,
                 from 3way.cpp:5:
misc.h:14:1: note: 'std::wstring' is defined in header '<string>'; did you forget to '#include <string>'?
   13 | #include "smartptr.h"
  +++ |+#include <string>
   14 | #include "stdcpp.h"

Fixes:
 - http://autobuild.buildroot.org/results/174fe03da7a40dd152703de93af6a213d9cac698

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>