package/llvm: fix host compile with gcc-13
Add upstream patch to fix host compile error on openSUSE Tumbleweed
(gcc-13.0.1).

Fixes:

  .../build/host-llvm-11.1.0/include/llvm/Support/Signals.h:117:8: error: variable or field ‘CleanupOnSignal’ declared void
    117 |   void CleanupOnSignal(uintptr_t Context);
        |        ^~~~~~~~~~~~~~~
  .../build/host-llvm-11.1.0/include/llvm/Support/Signals.h:117:24: error: ‘uintptr_t’ was not declared in this scope
    117 |   void CleanupOnSignal(uintptr_t Context);
        |                        ^~~~~~~~~
  .../build/host-llvm-11.1.0/include/llvm/Support/Signals.h:18:1: note: ‘uintptr_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
     17 | #include <string>
    +++ |+#include <cstdint>
     18 |

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit af3929cc45b842980d3cdc8dc35a8f76e8b008bd)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>