package/x11r7/xdriver_xf86-video-trident: fix build
Fix the following build failure raised since bump of xserver_xorg-server
to version 21.1.1 in commit d2b6519fb4c5961a0a36da054193854a4ee7bed4:

In file included from trident_bank.c:37:
trident.h:41:10: fatal error: xf86RamDac.h: No such file or directory
   41 | #include "xf86RamDac.h"
      |          ^~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/c81ac8075af257e8626d9d097270be7a7b4a1496

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>