Revert "package/x11r7/xlib_libXvMC: remove xlib_libXv dependency"
This reverts commit b8126ac1b3b74a6b1084e7b0dc7dc4eacd727575.

While looking at mesa3d package, I found this commit [1] about libxv
refering to an upstream commit [2].

The commit message is confusing "This library does not itself require
libXv for anything." but xv is still checked by the configure script
(pkg-config) and libXvMC still include Xvlib.h from XvMClib.h

In file included from XvMClibint.h:7:0,
                 from XvMC.c:5:
../include/X11/extensions/XvMClib.h:5:10: fatal error: X11/extensions/Xvlib.h:
No such file or directory
 #include <X11/extensions/Xvlib.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

So, xlib_libXv sill use xv library by including a header and using
XvImageFormatValues.

[1] https://cgit.freedesktop.org/mesa/mesa/commit/?id=2dbf10ba3d129d59e1a6c0e46b24c20629b277c6
[2] https://gitlab.freedesktop.org/xorg/lib/libxvmc/commit/dd9ae03725990ee9c9336bca4b267dfbb696002f

Fixes:
http://autobuild.buildroot.org/results/305/3051f4fbc1ab725de542a550e4f9eeb3cae385b8

Signed-off-by: Romain Naour <romain.naour@smile.fr>
Cc: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>