package/flac: fix build on ppc64
Disable vsx to avoid the following build failure on ppc64 raised since
bump to version 1.3.3 in commit d22325a2f0c504e4804cee801d3b4a1cb8cc5fa2
and
https://github.com/xiph/flac/commit/cdb030cd3749b4547399a049ce3cae5e974ccd48:

In file included from lpc_intrin_vsx.c:46:
/home/autobuild/autobuild/instance-1/output-1/host/lib/gcc/powerpc64-buildroot-linux-gnu/9.4.0/include/altivec.h:34:2: error: #error Use the "-maltivec" flag to enable PowerPC AltiVec support
   34 | #error Use the "-maltivec" flag to enable PowerPC AltiVec support
      |  ^~~~~
lpc_intrin_vsx.c: In function 'FLAC__lpc_compute_autocorrelation_intrin_power8_vsx_lag_16':
lpc_intrin_vsx.c:94:7: warning: implicit declaration of function 'vec_vsx_ld'; did you mean 'vec_vslh'? [-Wimplicit-function-declaration]
   94 |  d0 = vec_vsx_ld(0, base);
      |       ^~~~~~~~~~
      |       vec_vslh

Fixes:
 - http://autobuild.buildroot.org/results/a97a0522c58964fa51815236bc39b378e10b5008

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>