package/dtc: additional fix of include guards for older u-boot
With recent dtc but old u-boot, compilation issues occur related to libfdt.
These problems really are u-boot issue since it does not properly set
include paths so that its own headers are included. Nevertheless, since the
u-boot version is typically decided by users and stuck at some version
provided by a SoC or board vendor, it is not feasible to fix those old
versions.

Instead, already several fixes were made in the past, in Buildroot.
See commits:

3fa409a6d6a "package/dtc: fix include guards for older kernel/u-boot"
dcffc7a48fe "uboot: fix build for older uboot source trees"
f3e0da3dc2c "uboot: fix build when libfdt-devel is installed system-wide"
1e345796526 "uboot: ensure host includes are searched before system default
                includes"
92e43eebe39 "uboot: revert "uboot: use local libfdt.h""
09f5f1e0d7c "uboot: use local fdt headers"
3a6573ccee2 "uboot: use local libfdt.h"

Commit 3fa409a6d6aeb0b11cfb108b2c888ef4caf451c4 fixes the problem caused by
dtc having changed their include guards from _FOO_H to FOO_H (leading
underscore removed). Old u-boot would still use _FOO_H, which (combined with
host-dtc headers that use FOO_H) would cause the inclusion of two different
copies of the same nominal include file, e.g. libfdt.h or libfdt_env.h,
causing 'error: redefinition of xxx' compilation issues.
The fix sets the 'new' include guard when the 'old' one is detected,
preventing a second inclusion of the same nominal file.

For some u-boot versions, however, this change not only needs to be made in
libfdt.h and libfdt_env.h, but also in 'fdt.h'.

Update the dtc patch to do just that.

Signed-off-by: Thomas De Schampheleire <thomas.de_schampheleire@nokia.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>