package/dmalloc: fix strndup detection
Fix strndup detection as already done for strdup in commit
2e2c1ed258e50a9ab0afabcfceccb2a2892f85bc to avoid the following build
failure raised since bump to version 5.6.5 in commit
d363dbb92cacd0ec48f29451073cd8c2011b756e:

In file included from /nvmedata/autobuild/instance-0/output-1/host/mipsel-buildroot-linux-gnu/sysroot/usr/include/string.h:630:0,
                 from append.c:34:
dmalloc.h:396:7: error: expected identifier or '(' before '__extension__'
 char *strndup(const char *string, const DMALLOC_SIZE max_len);
       ^

Fixes:
 - http://autobuild.buildroot.org/results/2164dac43e2607a3570e8f98957a70f579d06cd3

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>