package/libressl: disable tests
Disable tests to avoid the following build failure since bump to version
3.5.2 in commit 1e9f000b0eff9359ce21df98542d44c5a52da254:

In file included from /nvmedata/autobuild/instance-11/output-1/host/aarch64_be-buildroot-linux-uclibc/sysroot/usr/include/stdio.h:71,
                 from /nvmedata/autobuild/instance-11/output-1/build/libressl-3.5.2/tests/../include/compat/stdio.h:18,
                 from /nvmedata/autobuild/instance-11/output-1/build/libressl-3.5.2/tests/rfc3779.c:18:
/nvmedata/autobuild/instance-11/output-1/host/aarch64_be-buildroot-linux-uclibc/sysroot/usr/include/bits/uClibc_stdio.h:149:23: error: expected identifier or '(' before ';' token
  149 |         void *__unused;                         /* Placeholder for codeset binding. */
      |                       ^

Fixes:
 - http://autobuild.buildroot.org/results/620cb8d542c2e0c263233f5b746cbc9be1bd9547

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>