package/netsnmp: fix musl build
Fix the following musl build failure raised since bump to version 5.9.4
in commit 7eb47439e6e2d845fc63a37348eb0b082ff874cc:

large_fd_set.c: In function 'LFD_SET':
../include/net-snmp/net-snmp-config.h:1614:30: error: unknown type name 'unknown'; did you mean 'union'?
 1614 | #define NETSNMP_FD_MASK_TYPE unknown
      |                              ^~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/394ebf93621c33dc2ddf370297268e6de9de7c9a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit bf55df8e3bef64f93b83b5063a0b59c2f459664f)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>