package/liburing: fix static build
Fix the following static build failure raised since the addition of the
package in commit 7ac9f78d5966d1d8998516065977eec0be98fe29:

>>> liburing 2.1 Installing to staging directory
PATH="/home/buildroot/autobuild/instance-3/output-1/host/bin:/home/buildroot/autobuild/instance-3/output-1/host/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" /usr/bin/make -j4 -C /home/buildroot/autobuild/instance-3/output-1/build/liburing-2.1 DESTDIR=/home/buildroot/autobuild/instance-3/output-1/host/arc-buildroot-linux-uclibc/sysroot install
make[1]: Entering directory '/home/buildroot/autobuild/instance-3/output-1/build/liburing-2.1'
sed -e "s%@prefix@%/usr%g" \
    -e "s%@libdir@%/usr/lib%g" \
    -e "s%@includedir@%/usr/include%g" \
    -e "s%@NAME@%liburing%g" \
    -e "s%@VERSION@%2.0%g" \
    liburing.pc.in >liburing.pc
make[2]: Entering directory '/home/buildroot/autobuild/instance-3/output-1/build/liburing-2.1/src'
     CC setup.os
     CC queue.os
     CC syscall.os
     CC register.os
     CC liburing.so.2.1.0
/home/buildroot/autobuild/instance-3/output-1/host/lib/gcc/arc-buildroot-linux-uclibc/10.2.0/../../../../arc-buildroot-linux-uclibc/bin/ld: /home/buildroot/autobuild/instance-3/output-1/host/arc-buildroot-linux-uclibc/sysroot/usr/lib/libc.a(__uClibc_main.os): in function `__uClibc_fini':
__uClibc_main.c:(.text+0xa2): undefined reference to `__fini_array_start'

Fixes:
 - http://autobuild.buildroot.org/results/54c67e0f5bd2b5f520a250dc13b5846f94fc1790

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>