package/cppcms: bump to version 2.0.0-beta2
- Update indentation in hash file (two spaces)
- This bump will fix the following build failure if python2 is not
  available on host (while at it, add host-python3 dependency):

Traceback (most recent call last):
  File "/home/autobuild/autobuild/instance-4/output-1/build/cppcms-1.2.1/bin/cppcms_tmpl_cc", line 14, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'

http://cppcms.com/wikipp/en/page/cppcms_2_0_whats_new

Fixes:
 - http://autobuild.buildroot.org/results/00482ee24deae95a91f8499f499b18e15f14b51a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>