package/qt6/qt6base: fix license
Commit 69eb9992493cb6cf70b71a2a3985b675e62e8dbf forgot to change the
licensing information which has been updated with
https://code.qt.io/cgit/qt/qtbase.git/commit/?id=05fc3aef53348fb58be6308076e000825b704e58
resulting in the following build failure:

ERROR: LICENSE.GPL2 has wrong sha256 hash:
ERROR: expected: 8177f97513213526df2cf6184d8ff986c675afb514d4e68a404010521b880643
ERROR: got     :

Fixes:
 - http://autobuild.buildroot.org/results/bf20b7457349f1bb7a82d471ad2c9e4307ac540c

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
[yann.morin.1998@free.fr:
  - one-item per line, both for _LICENSE and _LICENSE_FILES
  - fix check-package
]
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>