package/libsigsegv: fix musl build with powerpc
Fix the following musl build failure with powerpc raised since bump to
version 2.14 in commit fe7374dab1b707595915965003a24f0c99ede8f7:

In file included from fault.h:36,
                 from handler-unix.c:77,
                 from handler.c:19:
handler-unix.c: In function 'sigsegv_handler':
fault-linux-powerpc.h:35:73: error: 'mcontext_t' has no member named 'uc_regs'; did you mean 'gregs'?
   35 | #  define SIGSEGV_FAULT_STACKPOINTER  ((ucontext_t *) ucp)->uc_mcontext.uc_regs->gregs[1]
      |                                                                         ^~~~~~~
handler-unix.c:157:43: note: in expansion of macro 'SIGSEGV_FAULT_STACKPOINTER'
  157 |           uintptr_t old_sp = (uintptr_t) (SIGSEGV_FAULT_STACKPOINTER);
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/77b600071f07605be3ec28e2da46d6938e240087

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 4150c4d81cf7aed126e16f66c77a06df8c37050d)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>