package/sdl2_ttf: disable builtin harfbuzz
Disable builtin harfbuzz which is enabled by default since bump to
version 2.0.18 in commit f5b719cc64c6450ea4cc16b89f7959dbf9980923 and
https://github.com/libsdl-org/SDL_ttf/commit/834ec54127dc9c2a12928f5fe32cf110ec4c7a7f
resulting in the following build failure without threads:

In file included from external/harfbuzz-2.8.0/src/hb.hh:470,
                 from external/harfbuzz-2.8.0/src/hb-aat-layout.cc:28:
external/harfbuzz-2.8.0/src/hb-mutex.hh:53:10: fatal error: pthread.h: No such file or directory
   53 | #include <pthread.h>
      |          ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/ac8b366558bec61ada84ec15cf27652fde2b63b2

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>