package/taglib: fix build on sparc
Fix the following build failure on sparc raised since bump to version
1.12 in commit e98bcfd36209fd4dce5da9ce17ccb1fc4134ca1c:

/home/giuliobenetti/autobuild/run/instance-3/output-1/build/taglib-1.12/taglib/toolkit/trefcounter.cpp:55:21: error: duplicate 'volatile'
   55 | # define ATOMIC_INT volatile int
      |                     ^~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/387feeb6bcc190b3908e405ba5f8a888d7e1f348

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>