package/libexecinfo: needs dynamic library
Fix the following build failure raised since the addition of the package
in commit d92bb62c11a0632a4a6a658b762fb1819fd62570:

execinfo.c:32:10: fatal error: dlfcn.h: No such file or directory
   32 | #include <dlfcn.h>
      |          ^~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/ea33c8c6aa5091983837609eec5d129902183ef1

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>