package/transmission: fix build with autoconf >= 2.71
Fix the following build failure raised since bump of autoconf to version
2.70 in commit c5c3737382008b135c48377150eb276b1ca6f470:

ERROR: 'IT_PROG_INTLTOOL' must appear in configure.ac for intltool to work.

Fixes:
 - http://autobuild.buildroot.org/results/e8bea26f6b12adf16335b24836a7c5c31911af6a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>