package/optee-client: fix uclibc build
Fix the following uclibc build failure raised since bump to version
3.19.0 in commit 463d7a5b67b804807ed1805480690d3d39ae4136:

/tmp/instance-5/output-1/build/optee-client-3.19.0/libteeacl/src/group.c: In function 'teeacl_user_is_member_of':
/tmp/instance-5/output-1/build/optee-client-3.19.0/libteeacl/src/group.c:75:12: error: implicit declaration of function 'reallocarray' [-Werror=implicit-function-declaration]
   75 |   groups = reallocarray(groups, grouplistsize, sizeof(gid_t));
      |            ^~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/03eba71ab9b87676f2606ecf2a9b5a151fc396bb

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>