package/nginx-naxsi: needs pcre2
Commit 1665e92467a03beeafd46cf5ee8a2a17e60f8c56 forgot to update
nginx-naxsi resulting in the following build failure:

In file included from ../nginx-naxsi-d714f1636ea49a9a9f4f06dba14aee003e970834/naxsi_src/naxsi_runtime.c:7:
../nginx-naxsi-d714f1636ea49a9a9f4f06dba14aee003e970834/naxsi_src/naxsi.h:147:3: error: unknown type name 'ngx_regex_compile_t'
  147 |   ngx_regex_compile_t* target_rx;
      |   ^~~~~~~~~~~~~~~~~~~

Fixes: 1665e92467a03beeafd46cf5ee8a2a17e60f8c56
 - http://autobuild.buildroot.org/results/87bbcf946ccbd8e3bf1ca9f39464f4bb198c8d42

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit bf627af842739673256ec97575e84db817c73f5a)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>