package/libgeos: depends on wchar
libgeos unconditionally uses wstring which raises the following build
failure:

In file included from /srv/storage/autobuild/run/instance-3/output-1/build/libgeos-3.9.0/tools/astyle/ASLocalizer.cpp:40:
/srv/storage/autobuild/run/instance-3/output-1/build/libgeos-3.9.0/tools/astyle/ASLocalizer.h:72:34: error: 'wstring' does not name a type; did you mean 'stdin'?
  string convertToMultiByte(const wstring& wideStr) const;
                                  ^~~~~~~
                                  stdin

Fixes:
 - http://autobuild.buildroot.org/results/e97d03848d9bbf1845b994f391679a1dbf49f61e

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>