package/python-crossbar: add missing runtime dependency on python-werkzeug
Upstream commit
https://github.com/crossbario/crossbar/commit/b9c295d3cfa923b383f93fe534d40e42c56576dc
which has been part of the releases since v19.10.1 has added
werkzeug dependency.

Without werkzeug package, the test TestPythonPy3Crossbar
is failing at runtime with this error:

ModuleNotFoundError: No module named 'werkzeug'

Fixes:
https://gitlab.com/buildroot.org/buildroot/-/jobs/498144523

Signed-off-by: Romain Naour <romain.naour@gmail.com>
Cc: James Hilliard <james.hilliard1@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>