package/s390-tools: add zlib dependency
zlib is required to build s390-tools and cannot be disabled for now
due to libvmdump.

Fixes:

$BUILD_DIR/host/bin/s390x-buildroot-linux-gnu-g++ ... -c vmdump_convert.cpp -o vmdump_convert.o
lkcd_dump.cpp:15:10: fatal error: zlib.h: No such file or directory
   15 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.

Signed-off-by: Alexander Egorenkov <egorenar@linux.ibm.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>