package/pcre2: fix legal info
Commit 9cde02169756a14795cf0fd424f9a3a564fbd556 forgot to update hash of
LICENCE file (update in year:
https://github.com/PCRE2Project/pcre2/commit/3103b8f20a3b9944b177e812fde29fbfb8b90558):

 >>> pcre2 10.40 Collecting legal info
 ERROR: LICENCE has wrong sha256 hash:
 ERROR: expected: 15bc778a1f7e1f857d57abab4181749a06ad1d1f9420d5c9e3c23ef8c991b025
 ERROR: got     : 87d884eceb7fc54611470ce9f74280d28612b0c877adfc767e9676892a638987

Fixes:
 - http://autobuild.buildroot.org/results/275c5478d63d3d4016d440870e96f04230df69d6

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>