package/libglvnd: needs threads
Fix the following build failure raised since the addition of the package
in commit 69725563e969774c4861060bda7725b70dda85f6:

In file included from ../src/util/glvnd_pthread.c:39:
../src/util/glvnd_pthread.h:33:10: fatal error: pthread.h: No such file or directory
   33 | #include <pthread.h>
      |          ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/63624bafc6f7a225d4db0667df977fd6141561aa

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>