configs/visionfive: add missing host-openssl dependency for the kernel
The kernel build needs host-openssl:

certs/extract-cert.c:21:10: fatal error: openssl/bio.h: No such file or directory
   21 | #include <openssl/bio.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [scripts/Makefile.host:95: certs/extract-cert] Error 1
make[2]: *** [Makefile:1852: certs] Error 2
make[2]: *** Waiting for unfinished jobs....

Fixes:

  https://gitlab.com/buildroot.org/buildroot/-/jobs/3259660751

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>