package/libp11: bump to version 0.4.12
- Drop patch (already in version)
- This bump will also fix the following build failure with libressl raised
  since bump to version 3.5.2 in commit
  1e9f000b0eff9359ce21df98542d44c5a52da254:

  p11_cert.c: In function 'pkcs11_store_certificate':
  p11_cert.c:310:34: error: dereferencing pointer to incomplete type 'X509' {aka 'struct x509_st'}
    310 |  signature_nid = OBJ_obj2nid(x509->sig_alg->algorithm);
        |                                  ^~

https://github.com/OpenSC/libp11/releases/tag/libp11-0.4.12

Fixes:
 - http://autobuild.buildroot.org/results/3acfa1419b59f7daa58fa8e61abc63ecb00f853c

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>