package/rsh-redone: disable rlogind on musl
Commit 5eb9c5fc5b748b576aa013844b18722af30f49dc enabled linux-pam on
musl however rlogind fails to build on musl because it uses logwtmp:

/home/giuliobenetti/autobuild/run/instance-1/output-1/host/opt/ext-toolchain/bin/../lib/gcc/x86_64-buildroot-linux-musl/8.3.0/../../../../x86_64-buildroot-linux-musl/bin/ld: rlogind.c:(.text.startup+0x9ec): undefined reference to `logwtmp'

As this package is unmaintained, just disable back rlogind on musl

Fixes:
 - http://autobuild.buildroot.org/results/f2eb1c0bab7c6c32d6c561da0f85a530bd419206

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>