package/ola: fix build with libexecinfo
Fix the following build failure raised on uclibc and musl since the
reintroduction of the package in commit
1f74ddf62a1c98b65b2a4daa52a7c97c90579fae:

/home/giuliobenetti/autobuild/run/instance-3/output-1/host/opt/ext-toolchain/bin/../lib/gcc/arc-buildroot-linux-uclibc/10.2.0/../../../../arc-buildroot-linux-uclibc/bin/ld: common/.libs/libolacommon.so: undefined reference to `backtrace'

Fixes:
 - http://autobuild.buildroot.org/results/4362b20d786a0f44268ec32a689c23ac6d3b71c6

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>