libusbgx: fix build with glibc-2.28
Since https://sourceware.org/ml/libc-alpha/2015-11/msg00253.html sys/sysmacros.h
must be explicitly included.
Without sys/sysmacros.h and with glibc-2.28 build fails with error like:
src/.libs/libusbgx.so: undefined reference to minor' src/.libs/libusbgx.so: undefined reference tomajor'
src/.libs/libusbgx.so: undefined reference to `makedev'

backport pr #29 (https://github.com/libusbgx/libusbgx/pull/29) (now applied)

Fixes:

  http://autobuild.buildroot.net/results/872e2ab084c0c9bf466265d2f66140fbba692ee6/

Signed-off-by: Gwenhael Goavec-Merou <gwenhael.goavec-merou@trabucayre.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>