package/iperf: fix build without threads
Fix the following build failure without threads raised since bump to
version 2.1.8 in commit b05fc18a6bdc1308b895000092e98eb848611959:

Settings.cpp: In function 'void Settings_Interpret(char, const char*, thread_Settings*)':
Settings.cpp:1281:9: error: break statement not within loop or switch
 1281 |         break;
      |         ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/2bcddf8439f6913fdf19b1fc2d33999a787ab3b2

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>