package/libiconv: enable extra encodings
Quoting https://www.gnu.org/software/libiconv/

"When configured with the option --enable-extra-encodings, it also
 provides support for a few extra encodings:

European languages
    CP{437,737,775,852,853,855,857,858,860,861,863,865,869,1125}
Semitic languages
    CP864
Japanese
    EUC-JISX0213, Shift_JISX0213, ISO-2022-JP-3
Chinese
    BIG5-2003 (experimental)
Turkmen
    TDS565
Platform specifics
    ATARIST, RISCOS-LATIN1"

Updating Kodi from version 17.6 to 18.5 caused runtime errors on systems
with locale support disabled, here Kodi uses libiconv but needs CP437:

ERROR: customConvert: iconv_open() for "CP437" -> "UTF-8" failed,
 errno = 22 (Invalid argument)

Due to the size increase of libiconv.so.2.6.0 from 941K to 1,1M a new
Config.in option was added.

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
[yann.morin.1998@free.fr: fix check-package warning]
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>