package/zchunk: needs MMU
Fix the following build failure raised since the addition of the package
in commit 4ffa78fd60b66897473c2ac90f8055a998ad4cb6:

/home/giuliobenetti/autobuild/run/instance-0/output-1/host/opt/ext-toolchain/arm-buildroot-uclinux-uclibcgnueabi/bin/ld.real: src/zck_gen_zdict.p/zck_gen_zdict.c.o: in function `main':
zck_gen_zdict.c:(.text.startup+0x254): undefined reference to `fork'

Fixes:
 - http://autobuild.buildroot.org/results/582b994372435b8c35a56345c15bd0ffc722af79

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>