package/gerbera: fix build with fmt > 8.0
Fix the following build failure raised since bump of fmt to version
8.1.1 in commit c39af2c6797b0bac323e32fe93d68659d978e56b:

/home/peko/autobuild/instance-0/output-1/host/mips64el-buildroot-linux-uclibc/sysroot/usr/include/fmt/core.h:1728:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
       formattable,
       ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/009db44f83c3b02025c910ce4f190bd709c5ab49

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>