package/frr: fix elf_py TLS section handling
Fix the following build failure raised on mipsel, or1k, powerpc raised
since bump to version 8.1 in commit
a3fb39104b26423f1b0a45d0e7cecc6e7e0f8846:

struct.error: unpack requires a buffer of 20 bytes

Fixes:
 - http://autobuild.buildroot.org/results/74f39c6f14e3f60babdcabceb5e42656f69cdaa7

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>