package/grep: fix build with microblazeel and or1k
Fix the following build failure with microblazeel and or1k raised since
bump to version 3.7 in commit 40d60a7920f868757d92d45a8926c0a30537c0f0:

sigsegv.c: In function 'sigsegv_handler':
sigsegv.c:979:28: error: 'struct vma_struct' has no member named 'is_near_this'
  979 |                       : vma.is_near_this (addr, &vma))
      |

Fixes:
 - http://autobuild.buildroot.org/results/78142463ba8cc5f6c1bf15295095a271422294f4
 - http://autobuild.buildroot.org/results/f300b1b5e958f096a9d58197a44dcf0c2abd3585

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>