package/gnuradio: backport build fixes with less use of Boost
Backport patch from upstream to fix build failures such as:

    In file included from /home/buildroot/autobuild/instance-0/output-1/build/gnuradio-3.8.0.0/gr-digital/lib/glfsr.cc:23:
    /home/buildroot/autobuild/instance-0/output-1/build/gnuradio-3.8.0.0/gr-digital/lib/../include/gnuradio/digital/glfsr.h:42:5: error: 'uint32_t' does not name a type; did you mean 'u_int32_t'?
        uint32_t d_shift_register;
        ^~~~~~~~
        u_int32_t

Since Gnuradio policy is Less boost == better and C++11 is used, use cstdint
instead of boost/cstdint.hpp.

Applied in gnuradio master (475e4a156b516c089175afb998acdc80b740b437)

fix:
 - http://autobuild.buildroot.net/results/14015f499e58fee530877ac052878bbe2f799942/
 - http://autobuild.buildroot.net/results/53239f98dd5e03d4dc1bb4eb91ed765f77dbf0ec/

Signed-off-by: Gwenhael Goavec-Merou <gwenhael.goavec-merou@trabucayre.com>
[yann.morin.1998@free.fr:
  - add upstream reference in the patch itself
  - minor eye-candy in commit log
]
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>