package/libv4l: fix typeof related compile failure
In case Qt support is enabled use '-std=gnu++11' instead of '-std=c++11' to
enable c++11 support and gain support of the typeof GNU extension.

Fixes:

  - http://autobuild.buildroot.net/results/2d58906a1eefdf921b42f6c0d9fd680ef2ad6e27

  In file included from v4l2-ctl-streaming.cpp:14:
  ../../utils/common/v4l2-tpg.h: In function 'void tpg_s_hue(tpg_data*, s16)':
  ../../utils/common/v4l2-tpg.h:49:2: error: 'typeof' was not declared in this scope
     49 |  typeof(val) __val = (val);  \
        |  ^~~~~~

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>