iputils: Bump to version s20180629
Add upstream patch to fix build error:
ping.c: In function ‘main’:
ping.c:212:23: error: ‘AI_CANONIDN’ undeclared (first use in this function); did you mean ‘AI_CANONNAME’?
   hints.ai_flags &= ~ AI_CANONIDN;

Signed-off-by: Petr Vorel <petr.vorel@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>