package/python-can: add missing setuptools runtime dependency
The commit [1] removed setuptools from runtime dependencies
"Drop spurious setuptools runtime dependency.". Since then
the test TestPythonPy3Can fail with the following error:

  ModuleNotFoundError: No module named 'pkg_resources'

Add back setuptools to provide "pkg_resources".

Fixes
https://gitlab.com/buildroot.org/buildroot/-/jobs/4322819285

[1] 3001e2e1b90cbfb72ceb3b40dbd19a1b00eff871

Signed-off-by: Romain Naour <romain.naour@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit e1510a98da3a592d1ae151612e2bb9a3ba789d47)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>