package/rockchip-mali: fix armeb build
Fix the following armeb build failure raised since the addition of the
package in commit 7d6a9f53092d18d67ff661c69dab57ec8666898c:

ERROR: architecture for "/usr/lib/libmali-bifrost-g31-rxp0-gbm.so" is "AArch64", should be "ARM"

Fixes:
 - http://autobuild.buildroot.org/results/33ebfa936da8dfa4035db08a96f8872d7c9db6c3

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
[Arnout: instead of changing the condition to check for aarch64, add a
check for armeb]
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>