package/netdata: disable cloud
Disable cloud to avoid the following build failures raised since bump to
version 1.33.1 in commit 702170bc5c4acd35746a1cd399373c1ae79a69bd and
https://github.com/netdata/netdata/commit/e7e5d0c37242d8457e4b2610a95effe0db5ca1b1:

In file included from aclk/aclk.c:7:
aclk/aclk_otp.h:11:23: error: unknown type name 'RSA'
   11 | int aclk_get_mqtt_otp(RSA *p_key, char **mqtt_id, char **mqtt_usr, char **mqtt_pass, url_t *target);
      |                       ^~~
aclk/aclk.c:48:8: error: unknown type name 'RSA'
   48 | static RSA *aclk_private_key = NULL;
      |        ^~~
aclk/aclk.c: In function 'load_private_key':
aclk/aclk.c:52:9: warning: implicit declaration of function 'RSA_free' [-Wimplicit-function-declaration]
   52 |         RSA_free(aclk_private_key);
      |         ^~~~~~~~
aclk/aclk.c:65:5: error: unknown type name 'BIO'; did you mean 'EIO'?
   65 |     BIO *key_bio = BIO_new_mem_buf(private_key, -1);
      |     ^~~
      |     EIO

[...]

In file included from database/sqlite/../../aclk/aclk.h:6:0,
                 from database/sqlite/sqlite_aclk.c:10:
database/sqlite/../../aclk/aclk_util.h:6:29: fatal error: mqtt_wss_client.h: No such file or directory
compilation terminated.

Fixes:
 - http://autobuild.buildroot.org/results/6c87c0d1699fd518a989cb81a191419f427accc5
 - http://autobuild.buildroot.org/results/aa77c027316b45e812eaf9ced61fb8e967bb987f

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>