configs/freescale_imx7dsabresd: kernel build needs host-openssl
With the recent bump of the kernel to 4.19, the kernel configuration
now needs host-openssl to build.

Fixes:
scripts/extract-cert.c:21:10: fatal error: openssl/bio.h: No such file or directory
   21 | #include <openssl/bio.h>

Signed-off-by: Julien Olivain <julien.olivain@oss.nxp.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>