package/janus-gateway: fix build with libressl >= 3.5.0
Fix the following build failure with libressl raised since bump to
version 3.5.2 in commit 1e9f000b0eff9359ce21df98542d44c5a52da254:

dtls-bio.c:40:1: error: variable 'janus_dtls_bio_agent_methods' has initializer but incomplete type
   40 | static BIO_METHOD janus_dtls_bio_agent_methods = {
      | ^~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/92fe19446b40551c0139254d9efc6b3904fa287a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>