package/micropython: depends on host-python3
Replace BR2_PYTHON3_HOST_DEPENDENCY by host-python3 to avoid the
following build failure raised since bump to version 1.17 in commit
216dcdd95a355f1e8d79c95f887c2b5be07692d7:

Traceback (most recent call last):
  File "../py/makeversionhdr.py", line 117, in <module>
    make_version_header(sys.argv[1])
  File "../py/makeversionhdr.py", line 79, in make_version_header
    info = get_version_info_from_docs_conf()
  File "../py/makeversionhdr.py", line 67, in get_version_info_from_docs_conf
    for line in f:
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2154: ordinal not in range(128)

Indeed, this build failure is not reproduced by host-python3 (in version
3.9.7) so it is probably an issue with python 3.5 (which is 6-years old).

Fixes:
 - http://autobuild.buildroot.org/results/96f7b81f5d14715b0b6673a8016a31e9e1552d0b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Chris Packham <judge.packham@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>