package/pppd: always enable DES support in openssl
Fix commit d21d22dd06fda69b2c24a426642058f275af6548 which forgot to
always enable DES support in openssl resulting in the following build
failure with musl:

pppcrypt.c:65:22: error: 'DES_cblock' undeclared (first use in this function)
   65 |  DES_set_odd_parity((DES_cblock *)des_key);
      |                      ^~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/3a7358de6199bb069bd38139747e2d50f9416fd0

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>