package/lttng-libust: set -DUATOMIC_NO_LINK_ERROR
Set -DUATOMIC_NO_LINK_ERROR as suggested by upstream in
https://www.mail-archive.com/lttng-dev@lists.lttng.org/msg12950.html to
avoid the following build failure with lttng-tools raised since bump to
version 2.13.1 in commit 913e9e5dbdab52e18fc0eb8bc2fcb3fd97fec80d:

/home/buildroot/autobuild/instance-1/output-1/host/opt/ext-toolchain/bin/../lib/gcc/mips64el-buildroot-linux-gnu/9.3.0/../../../../mips64el-buildroot-linux-gnu/bin/ld: /home/buildroot/autobuild/instance-1/output-1/host/mips64el-buildroot-linux-gnu/sysroot/usr/lib/liblttng-ust-ctl.so: undefined reference to `_uatomic_link_error'

Fixes:
 - http://autobuild.buildroot.org/results/066c72f04b4c82df3c5c6a75d2eef232d4468612

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>