package/rtty: bump to version 8.1.0
This bump will fix the following build failure with wolfssl raised, at
least, since bump of wolfssl to version 5.5.0 in commit
04bb46c96e4486263c7b280185fb13f3261a266c:

/tmp/instance-18/output-1/build/rtty-7.4.0/src/ssl.c:75:5: error: unknown type name 'SSL_CTX'
   75 |     SSL_CTX *ctx;
      |     ^~~~~~~

https://github.com/zhaojh329/rtty/compare/v7.4.0...v8.1.0

Fixes:
 - http://autobuild.buildroot.org/results/d045d85890ca97accfcea6c13c94757485d867c2

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>