botan: disable documentation
Fix following error if sphinx is found but its version is too low:
Sphinx version error:
This project needs at least Sphinx v1.2 and therefore cannot be built with this version.
Ignoring ImportError and using old theme
  ERROR: Error running sphinx-build -q -c ./src/configs/sphinx -b html ./doc/manual build/docs/manual

Fixes:
 - http://autobuild.buildroot.net/results/c15715a05a41035954f32510483314060ea31260

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>