package/libusb: add -latomic to libusb-1.0.pc if needed
libusb unconditionally uses atomic since version 1.0.25 and
https://github.com/libusb/libusb/commit/1a08aa84d96397a3840a75abe66051f5360c2c84
resulting in the following build failure with pcsc-lite or openocd since
commit 9a0d11ebf9a255920e18a70916f2c8d367b6f21e:

checking for libusb_init... configure: error: libusb not found, use ./configure LIBUSB_LIBS=...

/home/buildroot/autobuild/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/sparc-buildroot-linux-uclibc/10.3.0/../../../../sparc-buildroot-linux-uclibc/bin/ld: /home/buildroot/autobuild/instance-0/output-1/host/sparc-buildroot-linux-uclibc/sysroot/usr/lib/libusb-1.0.so: undefined reference to `__atomic_fetch_add_4'
collect2: error: ld returned 1 exit status

Fixes:
 - http://autobuild.buildroot.org/results/4a27a769bb3cdf78643c3049b87d792178d6512c
 - http://autobuild.buildroot.org/results/b59b30cbe0e27399db5c7586f369104e68a1589a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>