board/pc: fix build failure due to new genimage 15
Actually genimage fails to create final image with:
```
ERROR: hdimage(disk.img): partition [MBR] (offset 0x1b8, size 0x48) overlaps previous partition boot (offset 0x0, size 0x200)
ERROR: hdimage(disk.img): bootloaders, etc. that overlap with the partition table must declare the overlapping area as a hole.
```

This is because genimage 15 is less permissive than before, so let's add
holes = {"(440; 512)"} to leave room to MBR.

The generated image is identical to the image generated by the previous
version of genimage.

Fixes:
https://gitlab.com/buildroot.org/buildroot/-/jobs/1865935249

Signed-off-by: Giulio Benetti <giulio.benetti@benettiengineering.com>
Tested-by: Giulio Benetti <giulio.benetti@benettiengineering.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>