package/exim: fix libressl build
Fix the following libressl build failure raised since bump to version
4.97 in commit daa5fd60c5b68611d19b0b4907209099a50c5b04 and
https://git.exim.org/exim.git/commit/6bf0021993572586f031ac7d973ca33358c2dac8:

In file included from tls.c:473:
tls-openssl.c: In function 'tls_client_stapling_cb':
tls-openssl.c:2652:11: error: invalid use of incomplete typedef 'OCSP_BASICRESP' {aka 'struct ocsp_basic_response_st'}
 2652 |         bs->certs
      |           ^~

Fixes: daa5fd60c5b68611d19b0b4907209099a50c5b04
 - http://autobuild.buildroot.org/results/869fde62128d7b0c65e0ac596a3a3f69b332583d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 2fea9e1b21929c4ff88d5df60131e8b61fe4a2df)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>