package/udpcast: fix musl build
Fix the following musl build failure raised since bump to version
20211207 in commit 11d573e84eb30e50911d8ef399921f3f0c01fdcd:

receivedata.c: In function 'findSlice':
receivedata.c:348:2: error: unknown type name 'ptrdiff_t'
  348 |  ptrdiff_t pos = slice - clst->slices;
      |  ^~~~~~~~~
receivedata.c:17:1: note: 'ptrdiff_t' is defined in header '<stddef.h>'; did you forget to '#include <stddef.h>'?
   16 | #include "fec.h"
  +++ |+#include <stddef.h>
   17 |

Fixes:
 - http://autobuild.buildroot.org/results/30208c6f175967fed6de690447a09e0c86547b24

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>