package/parted: needs gcc >= 5
Fix the following build failure raised since bump to version 3.5 in
commit a957171f718407cbe53a8aa5a40d1e11b6d00bf8 and
https://git.savannah.gnu.org/cgit/parted.git/commit/?id=15c49ec04f7eaff014d2e1eddd0aecf4150db63d:

gpt.c:181:5: error: initializer element is not constant
     { PED_PARTITION_APPLE_TV_RECOVERY,  PARTITION_APPLE_TV_RECOVERY_GUID },
     ^
gpt.c:181:5: error: (near initialization for 'flag_uuid_mapping[0].type_uuid')

Fixes: a957171f718407cbe53a8aa5a40d1e11b6d00bf8
 - http://autobuild.buildroot.org/results/1f0af75ec55da9052fbfb195a0699f84619eac81
 - http://autobuild.buildroot.org/results/438b5f40e8b393801f36c691d239e298998cb9d2

Note that udisks also select parted, but it already has a more stringent
dependency on GCC >= 7.

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit b26f0448e9ac2a9c8f68b47da4fc92f008b4407c)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>